packages:
  - apps/*
  - packages/*

catalog:
  "@orpc/client": ^1.12.2
  "@orpc/openapi": ^1.12.2
  "@orpc/server": ^1.12.2
  "@orpc/zod": ^1.12.2
  "@types/node": ^22.19.15
  better-auth: 1.5.2
  dotenv: ^17.3.1
  tsdown: ^0
  typescript: ^5.9.3
  zod: ^4.3.6
