// This file is auto-generated by @hey-api/openapi-ts

export const pageTokenSchema = {
    description: 'Base 64 encoded string used to determine the\nnext "page" of data to pull\n',
    type: 'string',
    format: 'byte',
    nullable: true
} as const;

export const baseLeagueSchema = {
    type: 'object',
    required: [
        'name',
        'slug'
    ],
    additionalProperties: false,
    properties: {
        name: {
            type: 'string',
            description: 'The name of the league',
            minLength: 1
        },
        slug: {
            type: 'string',
            description: 'URL friendly version of the league\'s name',
            minLength: 1
        }
    }
} as const;

export const simpleLeagueSchema = {
    allOf: [
        {
            $ref: '#/components/schemas/baseLeague'
        },
        {
            type: 'object',
            additionalProperties: false,
            required: [
                'id',
                'image'
            ],
            properties: {
                id: {
                    description: 'The league\'s ID',
                    type: 'string'
                },
                image: {
                    description: 'URL to an image of the League\'s logo',
                    type: 'string',
                    minLength: 1
                }
            }
        }
    ]
} as const;

export const extendedLeagueSchema = {
    allOf: [
        {
            $ref: '#/components/schemas/simpleLeague'
        },
        {
            type: 'object',
            additionalProperties: false,
            required: [
                'priority'
            ],
            properties: {
                priority: {
                    description: 'Unknown',
                    type: 'integer'
                }
            }
        }
    ]
} as const;

export const highlanderLeagueSchema = {
    allOf: [
        {
            $ref: '#/components/schemas/baseLeague'
        },
        {
            type: 'object',
            required: [
                'id',
                'guid',
                'region',
                'drupalId',
                'logoUrl',
                'createdAt',
                'updatedAt',
                'abouts',
                'names'
            ],
            additionalProperties: false,
            properties: {
                id: {
                    description: 'The league\'s ID',
                    type: 'integer'
                },
                guid: {
                    description: 'The [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier) for the league.\n',
                    type: 'string'
                },
                region: {
                    type: 'string'
                },
                drupalId: {
                    type: 'integer',
                    nullable: true
                },
                logoUrl: {
                    type: 'string'
                },
                createdAt: {
                    type: 'string',
                    description: 'The date and time when this entry was created.',
                    format: 'date-time'
                },
                updatedAt: {
                    type: 'string',
                    description: 'The date and time when this entry was last updated.',
                    format: 'date-time'
                },
                abouts: {
                    type: 'object',
                    description: 'Contains a description of the league translated in various languages.\n\nThe keys are presented in the format ([ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1)\nand [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2))\n\n`{languageCode}_{countryCode}`\n\nThe value is a string containing\nhtml tags representing the description in that specific locale.\n',
                    minProperties: 0,
                    additionalProperties: {
                        type: 'string'
                    }
                },
                names: {
                    type: 'object',
                    description: 'Contains the names of the league translated in various languages.\n\nThe keys are presented in the format ([ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1)\nand [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2))\n\n`{languageCode}_{countryCode}`\n\nThe value is a string containing\nthe name of the league in that specific locale.\n',
                    minProperties: 0,
                    additionalProperties: {
                        type: 'string'
                    }
                },
                tournaments: {
                    type: 'array',
                    description: 'An array containing the [UUIDs](https://en.wikipedia.org/wiki/Universally_unique_identifier)\nfor the tournaments in this league.\n',
                    items: {
                        type: 'string',
                        pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                    }
                }
            }
        }
    ]
} as const;

export const recordSchema = {
    type: 'object',
    nullable: true,
    description: 'Describes the amount of wins and losses the team has incurred\nin a particular stage of the tournament specifically group stage\n\nFor knockout phase, each series is treated individually.\n\nThis object is null when the match is ongoing and it is in the\nknockout stage.\n',
    additionalProperties: false,
    required: [
        'losses',
        'wins'
    ],
    properties: {
        losses: {
            type: 'integer',
            minLength: 1
        },
        wins: {
            type: 'integer',
            minLength: 1
        }
    }
} as const;

export const resultSchema = {
    type: 'object',
    additionalProperties: false,
    required: [
        'gameWins'
    ],
    properties: {
        gameWins: {
            type: 'integer',
            description: 'The number of games the team has won in that\nin the series\n',
            minLength: 1
        }
    }
} as const;

export const outcomeSchema = {
    type: 'string',
    nullable: true,
    description: 'Indicate whether the team won or lost the series\n\nThis will be null if the match is ongoing\n',
    enum: [
        'loss',
        'win'
    ]
} as const;

export const teamSchema = {
    type: 'object',
    additionalProperties: false,
    required: [
        'code',
        'image',
        'name'
    ],
    properties: {
        code: {
            type: 'string',
            minLength: 1
        },
        image: {
            type: 'string',
            minLength: 1
        },
        name: {
            type: 'string',
            minLength: 1
        }
    }
} as const;

export const customTeamSchema = {
    type: 'object',
    additionalProperties: false,
    required: [
        'id',
        'side'
    ],
    properties: {
        id: {
            $ref: '#/components/schemas/teamId'
        },
        side: {
            type: 'string',
            enum: [
                'blue',
                'red'
            ]
        }
    }
} as const;

export const extendedTeamSchema = {
    allOf: [
        {
            $ref: '#/components/schemas/team'
        },
        {
            type: 'object',
            additionalProperties: false,
            required: [
                'id',
                'slug',
                'alternativeImage',
                'homeLeague',
                'players'
            ],
            properties: {
                id: {
                    $ref: '#/components/schemas/teamId'
                },
                slug: {
                    $ref: '#/components/schemas/teamSlug'
                },
                alternativeImage: {
                    type: 'string',
                    minLength: 1
                },
                homeLeague: {
                    $ref: '#/components/schemas/homeLeague'
                },
                players: {
                    type: 'array',
                    items: {
                        $ref: '#/components/schemas/player'
                    }
                }
            }
        }
    ]
} as const;

export const homeLeagueSchema = {
    type: 'object',
    additionalProperties: false,
    required: [
        'name',
        'region'
    ],
    properties: {
        name: {
            type: 'string',
            description: 'The name of the league',
            minLength: 1
        },
        region: {
            type: 'string',
            description: 'The region where the league is located'
        }
    }
} as const;

export const teamSlugSchema = {
    type: 'string',
    description: 'The URL friendly version of the team name'
} as const;

export const teamIdSchema = {
    type: 'string',
    description: 'The team id'
} as const;

export const baseStrategySchema = {
    type: 'object',
    additionalProperties: false,
    required: [
        'count'
    ],
    properties: {
        count: {
            type: 'integer',
            enum: [
                1,
                3,
                5
            ]
        }
    }
} as const;

export const strategySchema = {
    allOf: [
        {
            $ref: '#/components/schemas/baseStrategy'
        },
        {
            type: 'object',
            additionalProperties: false,
            required: [
                'type'
            ],
            properties: {
                type: {
                    type: 'string',
                    enum: [
                        'bestOf'
                    ]
                }
            }
        }
    ]
} as const;

export const teamsSchema = {
    type: 'array',
    minItems: 2,
    maxItems: 2,
    items: {
        $ref: '#/components/schemas/team'
    }
} as const;

export const baseMatchSchema = {
    type: 'object',
    additionalProperties: false,
    required: [
        'teams'
    ],
    properties: {
        teams: {
            $ref: '#/components/schemas/teams'
        }
    }
} as const;

export const simpleMatchSchema = {
    allOf: [
        {
            $ref: '#/components/schemas/baseMatch'
        },
        {
            type: 'object',
            additionalProperties: false,
            required: [
                'id'
            ],
            properties: {
                id: {
                    description: 'The match id',
                    type: 'string'
                }
            }
        }
    ]
} as const;

export const stateSchema = {
    type: 'string',
    enum: [
        'completed',
        'unstarted',
        'inProgress'
    ]
} as const;

export const eventTypeSchema = {
    type: 'string',
    enum: [
        'match',
        'show'
    ]
} as const;

export const baseEventSchema = {
    type: 'object',
    properties: {
        match: {
            $ref: '#/components/schemas/baseMatch'
        }
    }
} as const;

export const simpleEventSchema = {
    type: 'object',
    additionalProperties: false,
    required: [
        'startTime',
        'blockName',
        'match'
    ],
    properties: {
        startTime: {
            type: 'string',
            description: 'The time the match started',
            format: 'date-time'
        },
        blockName: {
            type: 'string',
            nullable: true
        },
        match: {
            allOf: [
                {
                    $ref: '#/components/schemas/simpleMatch'
                },
                {
                    type: 'object',
                    additionalProperties: false,
                    required: [
                        'strategy',
                        'teams'
                    ],
                    properties: {
                        strategy: {
                            $ref: '#/components/schemas/strategy'
                        },
                        teams: {
                            type: 'array',
                            items: {
                                type: 'object',
                                additionalProperties: false,
                                required: [
                                    'result'
                                ],
                                properties: {
                                    result: {
                                        $ref: '#/components/schemas/result'
                                    }
                                }
                            }
                        }
                    }
                }
            ]
        }
    }
} as const;

export const extendedEventSchema = {
    allOf: [
        {
            $ref: '#/components/schemas/simpleEvent'
        },
        {
            type: 'object',
            additionalProperties: false,
            required: [
                'state',
                'type'
            ],
            properties: {
                state: {
                    $ref: '#/components/schemas/state'
                },
                type: {
                    $ref: '#/components/schemas/eventType'
                }
            }
        }
    ]
} as const;

export const tournamentSchema = {
    type: 'object',
    additionalProperties: false,
    required: [
        'endDate',
        'id',
        'slug',
        'startDate'
    ],
    properties: {
        endDate: {
            type: 'string',
            description: 'The date the tournament ends/ended.',
            format: 'full-date'
        },
        id: {
            type: 'string',
            description: 'This is the tournament id'
        },
        slug: {
            type: 'string'
        },
        startDate: {
            type: 'string',
            description: 'The date the tournament starts/started.',
            format: 'full-date'
        }
    }
} as const;

export const stageSchema = {
    type: 'object',
    description: 'Represents a stage in a tournament.\n\nWhether it is the group or knockout stage.\n',
    additionalProperties: false,
    required: [
        'name',
        'type',
        'slug',
        'sections'
    ],
    properties: {
        name: {
            type: 'string',
            description: 'The name of that stage of the tournament'
        },
        type: {
            type: 'string',
            description: 'The type of the stage.',
            enum: [
                'groups',
                'bracket'
            ]
        },
        slug: {
            type: 'string'
        },
        sections: {
            type: 'array',
            description: 'Each object in the array represents a particular round in that\nspecific stage in the tournament.\n\nFor the knockout stages, we could have the quarter finals,\nsemi finals and the finals under their own sections.\n\nFor the group stage, there is usually only one section.\n',
            items: {
                $ref: '#/components/schemas/section'
            }
        }
    }
} as const;

export const sectionSchema = {
    type: 'object',
    additionalProperties: false,
    required: [
        'name',
        'matches',
        'rankings'
    ],
    properties: {
        name: {
            type: 'string',
            description: 'The name of the section'
        },
        matches: {
            type: 'array',
            items: {
                allOf: [
                    {
                        $ref: '#/components/schemas/simpleMatch'
                    },
                    {
                        type: 'object',
                        additionalProperties: false,
                        required: [
                            'state',
                            'previousMatchIds',
                            'flags',
                            'teams'
                        ],
                        properties: {
                            state: {
                                $ref: '#/components/schemas/state'
                            },
                            previousMatchIds: {
                                type: 'array',
                                description: 'This stores the previous match ids for the teams in the current\nmatch were involved in.\n\nFor group stages this is usually null. For bracket stage it is\nused to indicate the matches that were played before the match\nin question.\n',
                                nullable: true,
                                items: {
                                    type: 'string'
                                }
                            },
                            flags: {
                                type: 'string',
                                nullable: true,
                                description: 'The purpose of this key is unknown. So far the only value it\nhas seems to be null.\n'
                            },
                            teams: {
                                type: 'array',
                                items: {
                                    type: 'object',
                                    additionalProperties: false,
                                    required: [
                                        'id',
                                        'slug',
                                        'result'
                                    ],
                                    properties: {
                                        id: {
                                            $ref: '#/components/schemas/teamId'
                                        },
                                        slug: {
                                            $ref: '#/components/schemas/teamSlug'
                                        },
                                        result: {
                                            allOf: [
                                                {
                                                    $ref: '#/components/schemas/result'
                                                },
                                                {
                                                    type: 'object',
                                                    additionalProperties: false,
                                                    required: [
                                                        'outcome'
                                                    ],
                                                    properties: {
                                                        outcome: {
                                                            $ref: '#/components/schemas/outcome'
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            }
                        }
                    }
                ]
            }
        },
        rankings: {
            type: 'array',
            description: 'Contains details about the actual standings for that particular\nsection\n\nThis is mostly used for the group stage. For the knockout stages, it\nis usually empty.\n',
            items: {
                $ref: '#/components/schemas/ranking'
            }
        }
    }
} as const;

export const rankingSchema = {
    type: 'object',
    additionalProperties: false,
    required: [
        'ordinal',
        'teams'
    ],
    properties: {
        ordinal: {
            type: 'integer',
            description: 'The league position'
        },
        teams: {
            type: 'array',
            description: 'The teams that are at that league position.\n\nIn most cases there will only be one team object in this array. In\ncases where several teams are tied with the same score, this array will\ncontain all teams tied for that position.\n',
            items: {
                allOf: [
                    {
                        $ref: '#/components/schemas/team'
                    },
                    {
                        type: 'object',
                        properties: {
                            id: {
                                $ref: '#/components/schemas/teamId'
                            },
                            slug: {
                                $ref: '#/components/schemas/teamSlug'
                            },
                            record: {
                                $ref: '#/components/schemas/record'
                            }
                        }
                    }
                ]
            }
        }
    }
} as const;

export const gameSchema = {
    type: 'object',
    additionalProperties: false,
    required: [
        'vods'
    ],
    properties: {
        vods: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/vod'
            }
        }
    }
} as const;

export const simpleGameSchema = {
    type: 'object',
    additionalProperties: false,
    required: [
        'id',
        'state',
        'number',
        'vods'
    ],
    properties: {
        id: {
            type: 'string',
            description: 'The game ID'
        },
        state: {
            $ref: '#/components/schemas/state'
        },
        number: {
            type: 'integer',
            description: 'The number of the game',
            enum: [
                1,
                2,
                3,
                4,
                5
            ]
        },
        vods: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/extendedVod'
            }
        }
    }
} as const;

export const extendedGameSchema = {
    allOf: [
        {
            $ref: '#/components/schemas/simpleGame'
        },
        {
            type: 'object',
            additionalProperties: false,
            required: [
                'teams'
            ],
            properties: {
                teams: {
                    type: 'array',
                    items: {
                        $ref: '#/components/schemas/customTeam'
                    }
                }
            }
        }
    ]
} as const;

export const vodSchema = {
    type: 'object',
    additionalProperties: false,
    required: [
        'parameter'
    ],
    properties: {
        parameter: {
            type: 'string'
        }
    }
} as const;

export const extendedVodSchema = {
    allOf: [
        {
            $ref: '#/components/schemas/vod'
        },
        {
            type: 'object',
            additionalProperties: false,
            required: [
                'locale',
                'provider',
                'offset'
            ],
            properties: {
                locale: {
                    $ref: '#/components/schemas/locale'
                },
                provider: {
                    type: 'string',
                    description: 'The platform that is hosting the vod\n',
                    enum: [
                        'youtube',
                        'twitch'
                    ]
                },
                offset: {
                    type: 'integer',
                    description: 'Purpose Unknown'
                }
            }
        }
    ]
} as const;

export const localeSchema = {
    type: 'string',
    description: 'This is the locale or language code using [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1)\nand [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)\n',
    enum: [
        'en-US',
        'en-GB',
        'en-AU',
        'cs-CZ',
        'de-DE',
        'el-GR',
        'es-ES',
        'es-MX',
        'fr-FR',
        'hu-HU',
        'it-IT',
        'pl-PL',
        'pt-BR',
        'ro-RO',
        'ru-RU',
        'tr-TR',
        'ja-JP',
        'ko-KR'
    ]
} as const;

export const playerSchema = {
    type: 'object',
    additionalProperties: false,
    required: [
        'id',
        'summonerName',
        'firstName',
        'lastName',
        'image',
        'role'
    ],
    properties: {
        id: {
            type: 'string'
        },
        summonerName: {
            type: 'string'
        },
        firstName: {
            type: 'string'
        },
        lastName: {
            type: 'string'
        },
        image: {
            type: 'string'
        },
        role: {
            type: 'string'
        }
    }
} as const;

export const windowSchema = {
    type: 'object',
    additionalProperties: false,
    required: [
        'esportsGameId',
        'esportsMatchId',
        'gameMetadata',
        'frames'
    ],
    properties: {
        esportsGameId: {
            type: 'string',
            description: 'The game Id of the match'
        },
        esportsMatchId: {
            type: 'string',
            description: 'The match Id of the match'
        },
        gameMetadata: {
            $ref: '#/components/schemas/gameMetadata'
        },
        frames: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/windowFrame'
            }
        }
    }
} as const;

export const gameMetadataSchema = {
    type: 'object',
    additionalProperties: false,
    required: [
        'patchVersion',
        'blueTeamMetadata',
        'redTeamMetadata'
    ],
    properties: {
        patchVersion: {
            type: 'string',
            description: 'The patch the match was played on'
        },
        blueTeamMetadata: {
            $ref: '#/components/schemas/teamMetadata'
        },
        redTeamMetadata: {
            $ref: '#/components/schemas/teamMetadata'
        }
    }
} as const;

export const teamMetadataSchema = {
    type: 'object',
    additionalProperties: false,
    required: [
        'esportsTeamId',
        'participantMetadata'
    ],
    properties: {
        esportsTeamId: {
            type: 'string',
            description: 'The team Id'
        },
        participantMetadata: {
            type: 'array',
            items: {
                oneOf: [
                    {
                        $ref: '#/components/schemas/participantMetadata'
                    },
                    {
                        $ref: '#/components/schemas/participantMetadataExtended'
                    }
                ]
            }
        }
    }
} as const;

export const participantMetadataSchema = {
    type: 'object',
    additionalProperties: false,
    required: [
        'participantId',
        'summonerName',
        'championId',
        'role'
    ],
    properties: {
        participantId: {
            $ref: '#/components/schemas/participantId'
        },
        summonerName: {
            type: 'string'
        },
        championId: {
            type: 'string'
        },
        role: {
            type: 'string',
            enum: [
                'top',
                'jungle',
                'mid',
                'bottom',
                'support'
            ]
        }
    }
} as const;

export const participantMetadataExtendedSchema = {
    allOf: [
        {
            $ref: '#/components/schemas/participantMetadata'
        },
        {
            type: 'object',
            additionalProperties: false,
            required: [
                'esportsPlayerId'
            ],
            properties: {
                esportsPlayerId: {
                    type: 'string'
                }
            }
        }
    ]
} as const;

export const participantIdSchema = {
    type: 'integer',
    enum: [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10
    ]
} as const;

export const baseFrameSchema = {
    type: 'object',
    additionalProperties: false,
    required: [
        'rfc460Timestamp'
    ],
    properties: {
        rfc460Timestamp: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const windowFrameSchema = {
    allOf: [
        {
            $ref: '#/components/schemas/baseFrame'
        },
        {
            type: 'object',
            additionalProperties: false,
            required: [
                'rfc460Timestamp',
                'gameState',
                'blueTeam',
                'redTeam'
            ],
            properties: {
                rfc460Timestamp: {
                    type: 'string',
                    format: 'date-time'
                },
                gameState: {
                    type: 'string',
                    enum: [
                        'in_game',
                        'finished'
                    ]
                },
                blueTeam: {
                    $ref: '#/components/schemas/teamStats'
                },
                redTeam: {
                    $ref: '#/components/schemas/teamStats'
                }
            }
        }
    ]
} as const;

export const detailsFrameSchema = {
    allOf: [
        {
            $ref: '#/components/schemas/baseFrame'
        },
        {
            type: 'object',
            additionalProperties: false,
            required: [
                'participants'
            ],
            properties: {
                participants: {
                    type: 'array',
                    minItems: 1,
                    maxItems: 10,
                    items: {
                        $ref: '#/components/schemas/extendedParticipantStats'
                    }
                }
            }
        }
    ]
} as const;

export const teamStatsSchema = {
    type: 'object',
    additionalProperties: false,
    required: [
        'totalGold',
        'inhibitors',
        'towers',
        'barons',
        'totalKills',
        'dragons',
        'participants'
    ],
    properties: {
        totalGold: {
            type: 'integer'
        },
        inhibitors: {
            type: 'integer'
        },
        towers: {
            type: 'integer'
        },
        barons: {
            type: 'integer'
        },
        totalKills: {
            type: 'integer'
        },
        dragons: {
            type: 'array',
            items: {
                type: 'string',
                enum: [
                    'ocean',
                    'mountain',
                    'infernal',
                    'cloud',
                    'elder'
                ]
            }
        },
        participants: {
            type: 'array',
            maxItems: 5,
            items: {
                $ref: '#/components/schemas/participantStats'
            }
        }
    }
} as const;

export const baseParticipantStatsSchema = {
    type: 'object',
    additionalProperties: false,
    required: [
        'participantId',
        'level',
        'kills',
        'deaths',
        'assists',
        'creepScore'
    ],
    properties: {
        participantId: {
            $ref: '#/components/schemas/participantId'
        },
        level: {
            type: 'integer'
        },
        kills: {
            type: 'integer'
        },
        deaths: {
            type: 'integer'
        },
        assists: {
            type: 'integer'
        },
        creepScore: {
            type: 'integer'
        }
    }
} as const;

export const participantStatsSchema = {
    allOf: [
        {
            $ref: '#/components/schemas/baseParticipantStats'
        },
        {
            type: 'object',
            additionalProperties: false,
            required: [
                'totalGold',
                'currentHealth',
                'maxHealth'
            ],
            properties: {
                totalGold: {
                    type: 'integer'
                },
                currentHealth: {
                    type: 'integer'
                },
                maxHealth: {
                    type: 'integer'
                }
            }
        }
    ]
} as const;

export const extendedParticipantStatsSchema = {
    allOf: [
        {
            $ref: '#/components/schemas/participantStats'
        },
        {
            type: 'object',
            additionalProperties: false,
            required: [
                'totalGoldEarned',
                'killParticipation',
                'championDamageShare',
                'wardsPlaced',
                'wardsDestroyed',
                'attackDamage',
                'abilityPower',
                'criticalChance',
                'attackSpeed',
                'lifeSteal',
                'armor',
                'magicResistance',
                'tenacity',
                'items',
                'perkMetadata',
                'abilities'
            ],
            properties: {
                totalGoldEarned: {
                    type: 'integer'
                },
                killParticipation: {
                    type: 'number',
                    format: 'float'
                },
                championDamageShare: {
                    type: 'number',
                    format: 'float'
                },
                wardsPlaced: {
                    type: 'integer'
                },
                wardsDestroyed: {
                    type: 'integer'
                },
                attackDamage: {
                    type: 'integer'
                },
                abilityPower: {
                    type: 'integer'
                },
                criticalChance: {
                    type: 'number',
                    format: 'float'
                },
                attackSpeed: {
                    type: 'integer'
                },
                lifeSteal: {
                    type: 'integer'
                },
                armor: {
                    type: 'integer'
                },
                magicResistance: {
                    type: 'integer'
                },
                tenacity: {
                    type: 'number',
                    format: 'float'
                },
                items: {
                    type: 'array',
                    maxItems: 7,
                    description: 'Contains the item Ids of the items in the inventory\n',
                    items: {
                        type: 'integer'
                    }
                },
                perkMetadata: {
                    $ref: '#/components/schemas/perkMetadata'
                },
                abilities: {
                    $ref: '#/components/schemas/abilities'
                }
            }
        }
    ]
} as const;

export const perkMetadataSchema = {
    type: 'object',
    additionalProperties: false,
    required: [
        'styleId',
        'subStyleId',
        'perks'
    ],
    properties: {
        styleId: {
            type: 'integer',
            description: 'The id of the primary rune path\n',
            enum: [
                8000,
                8100,
                8200,
                8300,
                8400
            ]
        },
        subStyleId: {
            type: 'integer',
            description: 'The id of the secondary rune path\n',
            enum: [
                8000,
                8100,
                8200,
                8300,
                8400
            ]
        },
        perks: {
            type: 'array',
            minItems: 9,
            maxItems: 9,
            description: 'The runes selected.\n\nIndex 0 - 3 are the ids of the primary runes\nIndex 4 - 5 are the ids of the secondary runes\nIndex 6 - 8 are the ids of the stats shard\n',
            items: {
                type: 'integer'
            }
        }
    }
} as const;

export const abilitiesSchema = {
    type: 'array',
    description: 'Contains the abilities the summoner levelled up at each level\n',
    maxItems: 18,
    enum: [
        'Q',
        'W',
        'E',
        'R'
    ],
    items: {
        type: 'string'
    }
} as const;

export const navItemSchema = {
    type: 'object',
    additionalProperties: false,
    required: [
        'id',
        'link',
        'slug',
        'label',
        'imageUrl',
        'order',
        'external',
        'parentNavItem',
        'createdAt',
        'updatedAt'
    ],
    properties: {
        id: {
            type: 'integer'
        },
        link: {
            type: 'string'
        },
        slug: {
            type: 'string',
            nullable: true
        },
        label: {
            type: 'string'
        },
        imageUrl: {
            type: 'string',
            nullable: true
        },
        order: {
            type: 'integer'
        },
        external: {
            type: 'boolean'
        },
        parentNavItem: {
            allOf: [
                {
                    $ref: '#/components/schemas/navItem'
                },
                {
                    type: 'object',
                    nullable: true
                }
            ]
        },
        createdAt: {
            type: 'string',
            description: 'The date and time when this entry was created.',
            format: 'date-time'
        },
        updatedAt: {
            type: 'string',
            description: 'The date and time when this entry was last updated.',
            format: 'date-time'
        }
    }
} as const;

export const videoSchema = {
    type: 'object',
    additionalProperties: false,
    required: [
        'id',
        'slug',
        'label',
        'locale',
        'reference',
        'source',
        'createdAt',
        'updatedAt',
        'game'
    ],
    properties: {
        id: {
            type: 'integer'
        },
        slug: {
            type: 'string',
            nullable: true
        },
        label: {
            type: 'string',
            nullable: true
        },
        locale: {
            type: 'string',
            description: 'The video\'s locale. The value is a [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1)\nlanguage code.\n'
        },
        reference: {
            type: 'string',
            pattern: '^urn:rg:lolesports:global:highlander:tournament:(?:[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}):game:(?:[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})$',
            description: 'Contains the tournament Id and the game Id of that match.\n'
        },
        source: {
            type: 'string',
            description: 'URL to the YouTube video of the match\n'
        },
        createdAt: {
            type: 'string',
            description: 'The date and time when this entry was created.',
            format: 'date-time'
        },
        updatedAt: {
            type: 'string',
            description: 'The date and time when this entry was last updated.',
            format: 'date-time'
        },
        game: {
            $ref: '#/components/schemas/gameId'
        }
    }
} as const;

export const gameIdSchema = {
    type: 'string',
    description: 'The game Id of the match.\n\nIt is a [UUID version 4](https://en.wikipedia.org/wiki/Universally_unique_identifier)\n',
    pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
} as const;

export const highlanderTournamentsSchema = {
    type: 'array',
    items: {
        $ref: '#/components/schemas/highlanderTournament'
    }
} as const;

export const highlanderTournamentSchema = {
    type: 'object',
    required: [
        'id',
        'title',
        'description',
        'leagueReference',
        'roles',
        'queues',
        'published',
        'rosters',
        'brackets',
        'liveMatches',
        'startDate',
        'endDate',
        'platformIds',
        'gameIds',
        'leagueId',
        'league'
    ],
    properties: {
        id: {
            type: 'string',
            pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$',
            description: 'The tournament Id\n\nIt is a [UUID version 4](https://en.wikipedia.org/wiki/Universally_unique_identifier)\n'
        },
        title: {
            type: 'string',
            description: 'URL friendly version of the tournament name'
        },
        description: {
            type: 'string',
            description: 'The tournament\'s name'
        },
        leagueReference: {
            type: 'string',
            pattern: '^urn:rg:lolesports:global:league:league:\\d+$',
            description: 'The integer in the string represents the league ID.'
        },
        roles: {
            $ref: '#/components/schemas/roles'
        },
        bracketType: {
            $ref: '#/components/schemas/bracketType'
        },
        matchType: {
            $ref: '#/components/schemas/matchType'
        },
        rosteringStrategy: {
            $ref: '#/components/schemas/rosteringStrategy'
        },
        seedingStrategy: {
            $ref: '#/components/schemas/rosteringStrategy'
        },
        queues: {
            type: 'object',
            minProperties: 0
        },
        rosters: {
            type: 'object',
            description: 'The keys to this object are [UUID version 4](https://en.wikipedia.org/wiki/Universally_unique_identifier)\nrepresenting the roster ID.\n\nTheir values are objects but they don\'t contain anything useful about the roster.\n',
            additionalProperties: {
                type: 'object',
                required: [
                    'id',
                    'name',
                    'roles',
                    'teamReference',
                    'substitutions',
                    'team'
                ],
                properties: {
                    id: {
                        type: 'string',
                        pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$',
                        description: 'The roster ID.\n\nIt is a [UUID version 4](https://en.wikipedia.org/wiki/Universally_unique_identifier)\n'
                    },
                    state: {
                        type: 'string',
                        enum: [
                            'eliminated'
                        ]
                    },
                    name: {
                        type: 'string',
                        description: 'The abbreviated version of the team\'s name.'
                    },
                    roles: {
                        type: 'object',
                        minProperties: 0
                    },
                    teamReference: {
                        type: 'string',
                        pattern: '^urn:rg:lolesports:global:team:team:\\d+$'
                    },
                    substitutions: {
                        type: 'object',
                        minProperties: 0
                    },
                    team: {
                        type: 'string',
                        pattern: '^\\d+$',
                        description: 'The Team ID'
                    }
                }
            }
        },
        published: {
            type: 'boolean',
            enum: [
                true,
                false
            ],
            description: 'If the value is true then the league/tournament has concluded, otherwise it is ongoing.\n'
        },
        breakpoints: {
            $ref: '#/components/schemas/breakpoints'
        },
        brackets: {
            $ref: '#/components/schemas/brackets'
        },
        standings: {
            $ref: '#/components/schemas/standings'
        },
        liveMatches: {
            type: 'array',
            description: 'The array contains [UUID version 4](https://en.wikipedia.org/wiki/Universally_unique_identifier) Match IDs\n\nDespite the name of this property it is unreliable as for some tournaments this array will\ncontain match IDs yet the matches are over.\n',
            items: {
                type: 'string',
                pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
            }
        },
        startDate: {
            type: 'string',
            description: 'The day the tournament starts/started.',
            format: 'date'
        },
        endDate: {
            type: 'string',
            description: 'The day the tournament ends/ended.',
            format: 'date'
        },
        platformIds: {
            type: 'array',
            description: 'Contains all the platform IDs in for this tournaments.\n\nA platform ID is combination of the gameRealm and the gameId.\nThe regex below describes the format.\n\n`^[A-Z]+\\d+:\\d+$`\n',
            items: {
                type: 'string'
            }
        },
        gameIds: {
            type: 'array',
            description: '\'Contains all the gameIds in this tournament.\n\n**Note:** The gameIds are in the format [UUID version 4](https://en.wikipedia.org/wiki/Universally_unique_identifier)\'\n',
            items: {
                type: 'string'
            }
        },
        leagueId: {
            type: 'string',
            description: 'The league ID',
            pattern: '^\\d+$'
        },
        league: {
            type: 'string',
            description: 'The league ID',
            pattern: '^\\d+$'
        }
    }
} as const;

export const rosteringStrategySchema = {
    type: 'object',
    required: [
        'identifier'
    ],
    properties: {
        identifier: {
            type: 'string',
            enum: [
                'passthru',
                'random'
            ]
        }
    }
} as const;

export const rolesSchema = {
    type: 'object',
    required: [
        'creator',
        'owner'
    ],
    properties: {
        creator: {
            type: 'array',
            minItems: 1,
            items: {
                $ref: '#/components/schemas/role'
            }
        },
        owner: {
            type: 'array',
            minItems: 1,
            items: {
                $ref: '#/components/schemas/role'
            }
        }
    }
} as const;

export const roleSchema = {
    type: 'object',
    required: [
        'origin',
        'region',
        'summonerName',
        'summonerLevel',
        'profileIconId',
        'admin'
    ],
    properties: {
        origin: {
            type: 'string',
            enum: [
                'BEARER_TOKEN'
            ]
        },
        region: {
            type: 'string',
            enum: [
                'global'
            ]
        },
        summonerName: {
            type: 'string',
            enum: [
                'test-user'
            ]
        },
        summonerLevel: {
            type: 'integer',
            enum: [
                0
            ]
        },
        profileIconId: {
            type: 'integer',
            enum: [
                0
            ]
        },
        admin: {
            type: 'boolean',
            enum: [
                true
            ]
        }
    }
} as const;

export const simpleRosterSchema = {
    type: 'object',
    properties: {
        roster: {
            type: 'string',
            pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$',
            description: 'The roster ID'
        }
    }
} as const;

export const breakpointsSchema = {
    type: 'object',
    description: 'The keys to this object are [UUID version 4](https://en.wikipedia.org/wiki/Universally_unique_identifier)\nrepresenting the roster ID.\n',
    additionalProperties: {
        type: 'object',
        required: [
            'id',
            'name',
            'position',
            'input',
            'scores',
            'roles',
            'generator'
        ],
        properties: {
            id: {
                type: 'string',
                pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$',
                description: 'The breakpoint\'s ID'
            },
            name: {
                type: 'string'
            },
            position: {
                type: 'integer'
            },
            input: {
                type: 'array',
                items: {
                    allOf: [
                        {
                            $ref: '#/components/schemas/simpleRoster'
                        },
                        {
                            type: 'object',
                            properties: {
                                bracket: {
                                    type: 'string',
                                    pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$',
                                    description: 'The bracket ID'
                                },
                                standing: {
                                    type: 'integer'
                                }
                            }
                        }
                    ]
                }
            },
            standings: {
                $ref: '#/components/schemas/standings'
            },
            scores: {
                $ref: '#/components/schemas/scores'
            },
            roles: {
                $ref: '#/components/schemas/roles'
            },
            generator: {
                type: 'object',
                properties: {
                    identifier: {
                        type: 'string',
                        enum: [
                            'noop'
                        ]
                    }
                }
            }
        }
    }
} as const;

export const standingsSchema = {
    type: 'object',
    required: [
        'result',
        'timestamp',
        'closed'
    ],
    properties: {
        result: {
            $ref: '#/components/schemas/highlanderResult'
        },
        timestamp: {
            type: 'integer',
            format: 'int64',
            description: 'Unix timestamp in milliseconds of when the match started.'
        },
        source: {
            type: 'string',
            enum: [
                'manual',
                'bestOf'
            ],
            description: 'How the record was created/updated.'
        },
        note: {
            type: 'string'
        },
        history: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/standings'
            }
        },
        closed: {
            type: 'boolean',
            description: 'If the value is true then the league/tournament has concluded, otherwise it is ongoing.\n',
            enum: [
                true,
                false
            ]
        }
    }
} as const;

export const highlanderResultSchema = {
    type: 'array',
    items: {
        type: 'array',
        items: {
            $ref: '#/components/schemas/simpleRoster'
        }
    }
} as const;

export const bracketsSchema = {
    type: 'object',
    description: 'The keys to this object are [UUID version 4](https://en.wikipedia.org/wiki/Universally_unique_identifier)\nrepresenting the bracket ID.\n',
    additionalProperties: {
        type: 'object',
        required: [
            'id',
            'name',
            'position',
            'groupPosition',
            'canManufacture',
            'state',
            'matches',
            'roles',
            'scores',
            'matchScores'
        ],
        properties: {
            id: {
                type: 'string',
                pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$',
                description: 'The bracket ID.'
            },
            name: {
                type: 'string',
                description: 'The name of the bracket'
            },
            position: {
                type: 'integer'
            },
            groupPosition: {
                type: 'integer'
            },
            groupName: {
                type: 'string'
            },
            canManufacture: {
                type: 'boolean'
            },
            state: {
                type: 'string',
                enum: [
                    'resolved',
                    'unresolved',
                    'unlinked'
                ],
                description: 'Whether it is ongoing or completed.\n\nThis is unreliable since some tournaments have the state unresolved yet they concluded\na long time ago.\n'
            },
            bracketType: {
                $ref: '#/components/schemas/bracketType'
            },
            matchType: {
                $ref: '#/components/schemas/matchType'
            },
            gameMode: {
                $ref: '#/components/schemas/gameMode'
            },
            input: {
                type: 'array',
                items: {
                    allOf: [
                        {
                            $ref: '#/components/schemas/simpleRoster'
                        },
                        {
                            type: 'object',
                            properties: {
                                breakpoint: {
                                    type: 'string',
                                    pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$',
                                    description: 'The breakpoint ID'
                                },
                                standing: {
                                    type: 'integer'
                                }
                            }
                        }
                    ]
                }
            },
            matches: {
                type: 'object',
                description: 'The keys to this object are [UUID version 4](https://en.wikipedia.org/wiki/Universally_unique_identifier)\nrepresenting the match ID.\n',
                additionalProperties: {
                    $ref: '#/components/schemas/highlanderMatch'
                }
            },
            standings: {
                $ref: '#/components/schemas/standings'
            },
            inheritableMatchScoringStrategy: {
                $ref: '#/components/schemas/scoring'
            },
            roles: {
                $ref: '#/components/schemas/roles'
            },
            scoring: {
                $ref: '#/components/schemas/scoring'
            },
            scores: {
                $ref: '#/components/schemas/scores'
            },
            matchScoring: {
                $ref: '#/components/schemas/scoring'
            },
            matchScores: {
                $ref: '#/components/schemas/scores'
            }
        }
    }
} as const;

export const bracketTypeSchema = {
    type: 'object',
    required: [
        'identifier'
    ],
    properties: {
        identifier: {
            type: 'string',
            enum: [
                'round_robin',
                'single_elim',
                'gauntlet',
                'bestOf'
            ]
        },
        options: {
            type: 'object',
            required: [
                'rounds'
            ],
            properties: {
                rounds: {
                    type: 'string',
                    pattern: '^\\d+$'
                }
            }
        }
    }
} as const;

export const matchTypeSchema = {
    type: 'object',
    required: [
        'identifier'
    ],
    properties: {
        identifier: {
            type: 'string',
            enum: [
                'bestOf',
                'single_elim'
            ]
        },
        options: {
            type: 'object',
            required: [
                'best_of'
            ],
            properties: {
                best_of: {
                    type: 'string',
                    pattern: '^\\d+$'
                }
            }
        }
    }
} as const;

export const gameModeSchema = {
    type: 'object',
    required: [
        'identifier',
        'requiredPlayers',
        'mapName'
    ],
    properties: {
        identifier: {
            type: 'string',
            enum: [
                'lol:duel',
                'lol:classic'
            ]
        },
        requiredPlayers: {
            type: 'integer',
            enum: [
                1,
                5
            ]
        },
        mapName: {
            type: 'string',
            enum: [
                'summoner_rift',
                'howling_abyss'
            ]
        }
    }
} as const;

export const highlanderMatchSchema = {
    type: 'object',
    required: [
        'id',
        'name',
        'position',
        'state',
        'groupPosition',
        'input',
        'games',
        'tiebreaker',
        'remadeGames',
        'roles',
        'scores'
    ],
    properties: {
        id: {
            type: 'string',
            pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$',
            description: 'The match ID'
        },
        name: {
            type: 'string'
        },
        position: {
            type: 'integer'
        },
        state: {
            '<<': {
                type: 'string',
                enum: [
                    'resolved',
                    'unresolved',
                    'unlinked'
                ],
                description: 'Whether it is ongoing or completed.\n\nThis is unreliable since some tournaments have the state unresolved yet they concluded\na long time ago.\n'
            },
            description: 'Whether it is ongoing or completed.\n'
        },
        groupPosition: {
            type: 'integer'
        },
        matchType: {
            $ref: '#/components/schemas/matchType'
        },
        gameMode: {
            $ref: '#/components/schemas/gameMode'
        },
        input: {
            type: 'array',
            items: {
                allOf: [
                    {
                        $ref: '#/components/schemas/simpleRoster'
                    },
                    {
                        oneOf: [
                            {
                                type: 'object',
                                properties: {
                                    match: {
                                        type: 'string',
                                        pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$',
                                        description: 'The match ID'
                                    }
                                }
                            },
                            {
                                type: 'object',
                                properties: {
                                    breakpoint: {
                                        type: 'string',
                                        pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$',
                                        description: 'The breakpoint ID'
                                    }
                                }
                            }
                        ]
                    },
                    {
                        type: 'object',
                        properties: {
                            standing: {
                                type: 'integer'
                            }
                        }
                    }
                ]
            }
        },
        games: {
            type: 'object',
            description: 'The keys to this object are [UUID version 4](https://en.wikipedia.org/wiki/Universally_unique_identifier)\nrepresenting the game ID.\n\nThese are the games played in that series.\n\nThe number of properties(key and value pair) in this object will be equal to the type of series that was\nplayed. For a best of 1 there will be only 1 game, 3 for best of 3s and 5 for best of 5s.\n',
            additionalProperties: {
                $ref: '#/components/schemas/highlanderGame'
            }
        },
        standings: {
            $ref: '#/components/schemas/standings'
        },
        tiebreaker: {
            type: 'boolean',
            enum: [
                true,
                false
            ]
        },
        remadeGames: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/highlanderGame'
            }
        },
        roles: {
            $ref: '#/components/schemas/roles'
        },
        scoring: {
            $ref: '#/components/schemas/scoring'
        },
        scores: {
            $ref: '#/components/schemas/scores'
        }
    }
} as const;

export const highlanderGameSchema = {
    type: 'object',
    required: [
        'id',
        'name',
        'generatedName',
        'input',
        'scores',
        'revision',
        'roles'
    ],
    properties: {
        id: {
            $ref: '#/components/schemas/gameId'
        },
        name: {
            type: 'string'
        },
        generatedName: {
            type: 'string'
        },
        state: {
            type: 'string',
            enum: [
                'remade'
            ]
        },
        gameMode: {
            $ref: '#/components/schemas/gameMode'
        },
        input: {
            type: 'array',
            items: {
                allOf: [
                    {
                        $ref: '#/components/schemas/simpleRoster'
                    },
                    {
                        oneOf: [
                            {
                                type: 'object',
                                properties: {
                                    match: {
                                        type: 'string',
                                        pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$',
                                        description: 'The match ID'
                                    }
                                }
                            },
                            {
                                type: 'object',
                                properties: {
                                    breakpoint: {
                                        type: 'string',
                                        pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$',
                                        description: 'The breakpoint ID'
                                    }
                                }
                            }
                        ]
                    },
                    {
                        type: 'object',
                        properties: {
                            standing: {
                                type: 'integer'
                            }
                        }
                    }
                ]
            }
        },
        standings: {
            $ref: '#/components/schemas/standings'
        },
        scores: {
            $ref: '#/components/schemas/scores'
        },
        gameId: {
            type: 'string',
            pattern: '^\\d+$',
            description: 'The numeric version of the game ID\n\nThis is what is used to access the ACS endpoint.\n'
        },
        gameRealm: {
            type: 'string',
            pattern: '^[A-Z]+\\d+$',
            description: 'The ID of the tournament realm on which the game was played on\n'
        },
        platformId: {
            type: 'string',
            pattern: '^[A-Z]+\\d+:\\d+$',
            description: 'A combination of the gameRealm and the gameId'
        },
        revision: {
            type: 'integer'
        },
        roles: {
            $ref: '#/components/schemas/roles'
        }
    }
} as const;

export const scoringSchema = {
    type: 'object',
    required: [
        'identifier',
        'options'
    ],
    properties: {
        identifier: {
            type: 'string',
            description: '**Note:** The `LegacyScoringStrategy` value has only been found in the 2015 worlds championship.',
            enum: [
                'standard',
                'LegacyScoringStrategy'
            ]
        },
        options: {
            type: 'object',
            required: [
                'points'
            ],
            properties: {
                points: {
                    type: 'array',
                    minItems: 2,
                    maxItems: 2,
                    items: {
                        type: 'integer'
                    }
                }
            }
        }
    }
} as const;

export const scoresSchema = {
    type: 'object',
    minProperties: 0,
    description: 'The keys to this object are [UUID version 4](https://en.wikipedia.org/wiki/Universally_unique_identifier)\nrepresenting the roster ID.\n',
    additionalProperties: {
        type: 'integer'
    }
} as const;

export const highlanderRecordsSchema = {
    type: 'array',
    items: {
        $ref: '#/components/schemas/highlanderRecord'
    }
} as const;

export const highlanderRecordSchema = {
    type: 'object',
    additionalProperties: false,
    required: [
        'wins',
        'losses',
        'ties',
        'score',
        'roster',
        'tournament',
        'bracket',
        'id'
    ],
    properties: {
        wins: {
            type: 'integer'
        },
        losses: {
            type: 'integer'
        },
        ties: {
            type: 'integer'
        },
        score: {
            type: 'integer'
        },
        roster: {
            type: 'string',
            description: 'The roster\'s [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier)',
            pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
        },
        tournament: {
            '<<': {
                type: 'string',
                description: 'The roster\'s [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier)',
                pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
            },
            description: 'The tournament\'s [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier)'
        },
        bracket: {
            '<<': {
                type: 'string',
                description: 'The roster\'s [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier)',
                pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
            },
            description: 'The bracket\'s [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier)'
        },
        id: {
            type: 'string',
            description: 'A combination of the bracket and roster UUIDs. The two are separated by a colon\\\n',
            pattern: '^(?:[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}):(?:[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})$'
        }
    }
} as const;

export const highlanderTeamSchema = {
    type: 'object',
    additionalProperties: false,
    required: [
        'id',
        'slug',
        'name',
        'guid',
        'teamPhotoUrl',
        'logoUrl',
        'acronym',
        'homeLeague',
        'altLogoUrl',
        'createdAt',
        'updatedAt',
        'bios',
        'foreignIds',
        'players',
        'starters',
        'subs'
    ],
    properties: {
        id: {
            type: 'integer',
            description: 'The team ID.'
        },
        slug: {
            type: 'string',
            description: 'URL friendly version of the team name.'
        },
        name: {
            type: 'string',
            description: 'The team name.'
        },
        guid: {
            type: 'string',
            description: 'The team\'s [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier).',
            pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
        },
        teamPhotoUrl: {
            type: 'string',
            nullable: true
        },
        logoUrl: {
            type: 'string',
            description: 'URL to an image of the team\'s logo.'
        },
        acronym: {
            type: 'string',
            description: 'The acronym form of the team name'
        },
        homeLeague: {
            type: 'string',
            description: 'Describes the league this team participates in during the regular seasons.\n',
            pattern: '^urn:rg:lolesports:global:league:league:\\d+$'
        },
        altLogoUrl: {
            type: 'string',
            nullable: true,
            description: 'Alternative URL to the team\'s logo.'
        },
        createdAt: {
            type: 'string',
            description: 'The date and time when this entry was created.',
            format: 'date-time'
        },
        updatedAt: {
            type: 'string',
            description: 'The date and time when this entry was last updated.',
            format: 'date-time'
        },
        bios: {
            type: 'object',
            description: 'Contains a description of the team translated to various languages.\n\nThe keys are presented in the format ([ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1)\nand [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2))\n\n`{languageCode}_{countryCode}`\n\nThe value is a string containing\nhtml tags representing the description in that specific locale.\n',
            additionalProperties: {
                type: 'string'
            }
        },
        foreignIds: {
            $ref: '#/components/schemas/foreignIds'
        },
        players: {
            type: 'array',
            description: 'An array containing the player IDs for those belonging in that team.',
            items: {
                type: 'integer'
            }
        },
        starters: {
            type: 'array',
            description: 'An array of the player IDs of those in the main roster',
            items: {
                type: 'integer'
            }
        },
        subs: {
            type: 'array',
            description: 'An array of the player IDs of the subs.',
            items: {
                type: 'integer'
            }
        }
    }
} as const;

export const foreignIdsSchema = {
    type: 'object',
    properties: {
        drupalId: {
            type: 'string'
        }
    }
} as const;

export const highlanderPlayerSchema = {
    type: 'object',
    additionalProperties: false,
    required: [
        'id',
        'slug',
        'name',
        'firstName',
        'lastName',
        'roleSlug',
        'photoUrl',
        'hometown',
        'region',
        'birthdate',
        'createdAt',
        'updatedAt',
        'bios',
        'foreignIds',
        'socialNetworks',
        'champions'
    ],
    properties: {
        id: {
            type: 'integer',
            description: 'The player ID'
        },
        slug: {
            type: 'string',
            description: 'URL friendly version of the player\'s in game name'
        },
        name: {
            type: 'string',
            description: 'The player\'s in game name'
        },
        firstName: {
            type: 'string'
        },
        LastName: {
            type: 'string',
            nullable: true
        },
        roleSlug: {
            type: 'string',
            description: 'The role they usually play'
        },
        photoUrl: {
            type: 'string',
            nullable: true,
            description: 'URL to the player\'s photo'
        },
        hometown: {
            type: 'string',
            nullable: true
        },
        region: {
            type: 'string'
        },
        birthdate: {
            type: 'string',
            format: 'date-time',
            nullable: true
        },
        createdAt: {
            type: 'string',
            description: 'The date and time when this entry was created.',
            format: 'date-time'
        },
        updatedAt: {
            type: 'string',
            description: 'The date and time when this entry was last updated.',
            format: 'date-time'
        },
        bios: {
            type: 'object',
            description: 'Contains a description of the player translated to various languages.\n\nThe keys are presented in the format ([ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1)\nand [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2))\n\n`{languageCode}_{countryCode}`\n\nThe value is a string containing\nhtml tags representing the description in that specific locale.\n',
            additionalProperties: {
                type: 'string'
            }
        },
        foreignIds: {
            allOf: [
                {
                    $ref: '#/components/schemas/foreignIds'
                },
                {
                    type: 'object',
                    description: '\'This object may contain keys which are the names of various tournament realms.\n\n**Example:** `ESPORTSTMNT02: "200008392"`\n\nThe purpose of the value in those strings is unknown.\'\n',
                    additionalProperties: {
                        type: 'string'
                    }
                }
            ]
        },
        socialNetworks: {
            type: 'object',
            description: 'Contains links to the player\'s social media accounts.\n\nThe key is the name of the social media platform and the value is the URL\n',
            additionalProperties: {
                type: 'string'
            }
        },
        champions: {
            type: 'array',
            items: {
                type: 'object',
                additionalProperties: false,
                required: [
                    'id',
                    'playerId',
                    'championId',
                    'championKey',
                    'championName',
                    'createdAt',
                    'updatedAt'
                ],
                properties: {
                    id: {
                        type: 'integer'
                    },
                    playerId: {
                        type: 'integer',
                        description: 'The player ID'
                    },
                    championId: {
                        type: 'integer',
                        description: 'The champion ID'
                    },
                    championKey: {
                        type: 'string',
                        description: 'The champion\'s name'
                    },
                    championName: {
                        type: 'string',
                        description: 'The champion\'s name'
                    },
                    createdAt: {
                        type: 'string',
                        description: 'The date and time when this entry was created.',
                        format: 'date-time'
                    },
                    updatedAt: {
                        type: 'string',
                        description: 'The date and time when this entry was last updated.',
                        format: 'date-time'
                    }
                }
            }
        }
    }
} as const;

export const highlanderTeamsSchema = {
    type: 'array',
    description: 'An array containing the teams that have participated in this league.\n',
    items: {
        $ref: '#/components/schemas/highlanderTeam'
    }
} as const;

export const highlanderPlayersSchema = {
    type: 'array',
    items: {
        $ref: '#/components/schemas/highlanderPlayer'
    }
} as const;

export const baseScheduleItemSchema = {
    type: 'object',
    additionalProperties: false,
    required: [
        'id',
        'scheduledTime',
        'tags',
        'tournament',
        'league'
    ],
    properties: {
        id: {
            description: 'The schedule item ID.',
            type: 'string'
        },
        scheduledTime: {
            type: 'string',
            format: 'date-time',
            description: 'The time the match/event is/was scheduled to start.'
        },
        tags: {
            $ref: '#/components/schemas/tags'
        },
        tournament: {
            type: 'string',
            pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$',
            description: 'The tournament ID'
        },
        league: {
            type: 'string',
            description: 'The League ID'
        }
    }
} as const;

export const matchScheduleItemSchema = {
    allOf: [
        {
            $ref: '#/components/schemas/baseScheduleItem'
        },
        {
            type: 'object',
            additionalProperties: false,
            required: [
                'content',
                'match',
                'bracket'
            ],
            properties: {
                content: {
                    type: 'string',
                    pattern: '^urn:rg:lolesports:global:highlander:tournament:(?:[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}):match:(?:[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})$',
                    description: 'Contains the tournament and match Ids for the specific match.\n'
                },
                match: {
                    type: 'string',
                    pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$',
                    description: 'The match ID'
                },
                bracket: {
                    type: 'string',
                    pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$',
                    description: 'The bracket ID'
                }
            }
        }
    ]
} as const;

export const eventScheduleItemSchema = {
    allOf: [
        {
            $ref: '#/components/schemas/baseScheduleItem'
        },
        {
            type: 'object',
            additionalProperties: false,
            required: [
                'content'
            ],
            properties: {
                content: {
                    type: 'string',
                    pattern: '^{\\\\"imageUrl\\\\":null,\\\\"label\\\\":\\\\"(?:rebroadcast|pt1|opening-ceremony|worlds-pre-show)\\\\"}$'
                }
            }
        }
    ]
} as const;

export const scheduleItemSchema = {
    oneOf: [
        {
            $ref: '#/components/schemas/matchScheduleItem'
        },
        {
            $ref: '#/components/schemas/eventScheduleItem'
        }
    ]
} as const;

export const tagsSchema = {
    type: 'object',
    additionalProperties: false,
    required: [
        'leagueLabel',
        'tournamentLabel',
        'blockLabel',
        'subBlockLabel',
        'subBlockPrefix'
    ],
    description: 'The labels are used to describe the week and day the match/event is taking place in.\nAlso, it could indicate the stage of the tournament.\n\nThe blockPrefix comes before the block Label. Same with the subBlockPrefix and the subBlockLabel.\n',
    properties: {
        subBlockLabel: {
            type: 'string'
        },
        blockLabel: {
            type: 'string'
        },
        leagueLabel: {
            type: 'string',
            pattern: '^urn:rg:lolesports:global:league:league:\\d+$'
        },
        blockPrefix: {
            type: 'string'
        },
        subBlockPrefix: {
            type: 'string'
        },
        yearLabel: {
            type: 'string'
        },
        stageLabel: {
            type: 'string',
            pattern: '^urn:rg:lolesports:global:highlander:tournament:(?:[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}):bracket:(?:[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})$',
            description: 'Contains the tournament and bracket Ids the match/event belongs to.\n'
        },
        tournamentLabel: {
            type: 'string',
            pattern: '^urn:rg:lolesports:global:highlander:tournament:(?:[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})$',
            description: 'Contains the tournament ID.\n'
        }
    }
} as const;
