// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetCompletedEventsData, GetCompletedEventsResponses, GetDetailsData, GetDetailsResponses, GetEventDetailsData, GetEventDetailsResponses, GetGamesData, GetGamesResponses, GetLeaguesData, GetLeaguesResponses, GetLiveData, GetLiveResponses, GetScheduleData, GetScheduleResponses, GetStandingsData, GetStandingsResponses, GetTeamsData, GetTeamsResponses, GetTournamentsForLeagueData, GetTournamentsForLeagueResponses, GetWindowData, GetWindowResponses, HighlanderTournamentsData, HighlanderTournamentsErrors, HighlanderTournamentsResponses, LeaguesData, LeaguesErrors, LeaguesResponses, NavItemsData, NavItemsResponses, PlayersData, PlayersResponses, ScheduleItemsData, ScheduleItemsResponses, TeamsData, TeamsResponses, VideosData, VideosResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getLeagues = <ThrowOnError extends boolean = false>(options: Options<GetLeaguesData, ThrowOnError>) => (options.client ?? client).get<GetLeaguesResponses, unknown, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/getLeagues',
    ...options
});

export const getSchedule = <ThrowOnError extends boolean = false>(options: Options<GetScheduleData, ThrowOnError>) => (options.client ?? client).get<GetScheduleResponses, unknown, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/getSchedule',
    ...options
});

export const getLive = <ThrowOnError extends boolean = false>(options: Options<GetLiveData, ThrowOnError>) => (options.client ?? client).get<GetLiveResponses, unknown, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/getLive',
    ...options
});

export const getTournamentsForLeague = <ThrowOnError extends boolean = false>(options: Options<GetTournamentsForLeagueData, ThrowOnError>) => (options.client ?? client).get<GetTournamentsForLeagueResponses, unknown, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/getTournamentsForLeague',
    ...options
});

export const getStandings = <ThrowOnError extends boolean = false>(options: Options<GetStandingsData, ThrowOnError>) => (options.client ?? client).get<GetStandingsResponses, unknown, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/getStandings',
    ...options
});

export const getCompletedEvents = <ThrowOnError extends boolean = false>(options: Options<GetCompletedEventsData, ThrowOnError>) => (options.client ?? client).get<GetCompletedEventsResponses, unknown, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/getCompletedEvents',
    ...options
});

export const getEventDetails = <ThrowOnError extends boolean = false>(options: Options<GetEventDetailsData, ThrowOnError>) => (options.client ?? client).get<GetEventDetailsResponses, unknown, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/getEventDetails',
    ...options
});

export const getTeams = <ThrowOnError extends boolean = false>(options: Options<GetTeamsData, ThrowOnError>) => (options.client ?? client).get<GetTeamsResponses, unknown, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/getTeams',
    ...options
});

export const getGames = <ThrowOnError extends boolean = false>(options: Options<GetGamesData, ThrowOnError>) => (options.client ?? client).get<GetGamesResponses, unknown, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/getGames',
    ...options
});

export const getWindow = <ThrowOnError extends boolean = false>(options: Options<GetWindowData, ThrowOnError>) => (options.client ?? client).get<GetWindowResponses, unknown, ThrowOnError>({ url: '/window/{gameId}', ...options });

export const getDetails = <ThrowOnError extends boolean = false>(options: Options<GetDetailsData, ThrowOnError>) => (options.client ?? client).get<GetDetailsResponses, unknown, ThrowOnError>({ url: '/details/{gameId}', ...options });

export const navItems = <ThrowOnError extends boolean = false>(options?: Options<NavItemsData, ThrowOnError>) => (options?.client ?? client).get<NavItemsResponses, unknown, ThrowOnError>({ url: '/navItems', ...options });

/**
 * This endpoint returns details about esports vods on YouTube.
 *
 * The data returned by this endpoint is fairly large (more than 5MB) since
 * it includes vods from 2015 up to (at the time of writing this) June 2019
 * and it will continue growing.
 *
 * Do consider this when dealing with clients (like mobile phones) where
 * bandwidth and memory may be scarce.
 *
 * It is highly advised that you cache the data from this endpoint.
 *
 */
export const videos = <ThrowOnError extends boolean = false>(options?: Options<VideosData, ThrowOnError>) => (options?.client ?? client).get<VideosResponses, unknown, ThrowOnError>({ url: '/videos', ...options });

/**
 * If a league does not have highlanderTournament objects, the API will return 404
 *
 */
export const highlanderTournaments = <ThrowOnError extends boolean = false>(options: Options<HighlanderTournamentsData, ThrowOnError>) => (options.client ?? client).get<HighlanderTournamentsResponses, HighlanderTournamentsErrors, ThrowOnError>({ url: '/highlanderTournaments', ...options });

export const leagues = <ThrowOnError extends boolean = false>(options: Options<LeaguesData, ThrowOnError>) => (options.client ?? client).get<LeaguesResponses, LeaguesErrors, ThrowOnError>({ url: '/leagues', ...options });

export const scheduleItems = <ThrowOnError extends boolean = false>(options: Options<ScheduleItemsData, ThrowOnError>) => (options.client ?? client).get<ScheduleItemsResponses, unknown, ThrowOnError>({ url: '/scheduleItems', ...options });

/**
 * If the `teamStatsSummaries`, `teamRosterStats` and `teamStatsHistories` keys are not present,
 * then the team did not take part in that particular tournament.
 *
 */
export const teams = <ThrowOnError extends boolean = false>(options: Options<TeamsData, ThrowOnError>) => (options.client ?? client).get<TeamsResponses, unknown, ThrowOnError>({ url: '/teams', ...options });

/**
 * If the `playerStatsSummaries` and `playerStatsHistories` keys are not present,
 * then the player did not take part in that particular tournament.
 *
 */
export const players = <ThrowOnError extends boolean = false>(options: Options<PlayersData, ThrowOnError>) => (options.client ?? client).get<PlayersResponses, unknown, ThrowOnError>({ url: '/players', ...options });
