// This file is auto-generated by @hey-api/openapi-ts

import type { GetCompletedEventsResponse, GetDetailsResponse, GetLiveResponse, GetScheduleResponse, GetWindowResponse, HighlanderTournamentsResponse, LeaguesResponse, NavItemsResponse, PlayersResponse, ScheduleItemsResponse, TeamsResponse, VideosResponse } from './types.gen';

const simpleEventSchemaResponseTransformer = (data: any) => {
    data.startTime = new Date(data.startTime);
    return data;
};

const extendedEventSchemaResponseTransformer = (data: any) => {
    data = simpleEventSchemaResponseTransformer(data);
    return data;
};

export const getScheduleResponseTransformer = async (data: any): Promise<GetScheduleResponse> => {
    data.data.schedule.updated = new Date(data.data.schedule.updated);
    data.data.schedule.events = data.data.schedule.events.map((item: any) => extendedEventSchemaResponseTransformer(item));
    return data;
};

export const getLiveResponseTransformer = async (data: any): Promise<GetLiveResponse> => {
    if (data.data.schedule.events) {
        data.data.schedule.events = data.data.schedule.events.map((item: any) => extendedEventSchemaResponseTransformer(item));
    }
    return data;
};

export const getCompletedEventsResponseTransformer = async (data: any): Promise<GetCompletedEventsResponse> => {
    data.data.schedule.events = data.data.schedule.events.map((item: any) => simpleEventSchemaResponseTransformer(item));
    return data;
};

const baseFrameSchemaResponseTransformer = (data: any) => {
    data.rfc460Timestamp = new Date(data.rfc460Timestamp);
    return data;
};

const windowFrameSchemaResponseTransformer = (data: any) => {
    data = baseFrameSchemaResponseTransformer(data);
    data.rfc460Timestamp = new Date(data.rfc460Timestamp);
    return data;
};

const windowSchemaResponseTransformer = (data: any) => {
    data.frames = data.frames.map((item: any) => windowFrameSchemaResponseTransformer(item));
    return data;
};

export const getWindowResponseTransformer = async (data: any): Promise<GetWindowResponse> => {
    data = windowSchemaResponseTransformer(data);
    return data;
};

const detailsFrameSchemaResponseTransformer = (data: any) => {
    data = baseFrameSchemaResponseTransformer(data);
    return data;
};

export const getDetailsResponseTransformer = async (data: any): Promise<GetDetailsResponse> => {
    data.frames = data.frames.map((item: any) => detailsFrameSchemaResponseTransformer(item));
    return data;
};

const navItemSchemaResponseTransformer = (data: any) => {
    data.parentNavItem = navItemSchemaResponseTransformer(data.parentNavItem);
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

const highlanderLeagueSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const navItemsResponseTransformer = async (data: any): Promise<NavItemsResponse> => {
    data.navItems = data.navItems.map((item: any) => navItemSchemaResponseTransformer(item));
    data.leagues = data.leagues.map((item: any) => highlanderLeagueSchemaResponseTransformer(item));
    return data;
};

const videoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const videosResponseTransformer = async (data: any): Promise<VideosResponse> => {
    data.videos = data.videos.map((item: any) => videoSchemaResponseTransformer(item));
    return data;
};

const standingsSchemaResponseTransformer = (data: any) => {
    data.timestamp = BigInt(data.timestamp.toString());
    if (data.history) {
        data.history = data.history.map((item: any) => standingsSchemaResponseTransformer(item));
    }
    return data;
};

const highlanderTournamentSchemaResponseTransformer = (data: any) => {
    if (data.standings) {
        data.standings = standingsSchemaResponseTransformer(data.standings);
    }
    data.startDate = new Date(data.startDate);
    data.endDate = new Date(data.endDate);
    return data;
};

const highlanderTournamentsSchemaResponseTransformer = (data: any) => {
    data = data.map((item: any) => highlanderTournamentSchemaResponseTransformer(item));
    return data;
};

export const highlanderTournamentsResponseTransformer = async (data: any): Promise<HighlanderTournamentsResponse> => {
    data = highlanderTournamentsSchemaResponseTransformer(data);
    return data;
};

const highlanderTeamSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

const highlanderTeamsSchemaResponseTransformer = (data: any) => {
    data = data.map((item: any) => highlanderTeamSchemaResponseTransformer(item));
    return data;
};

const highlanderPlayerSchemaResponseTransformer = (data: any) => {
    if (data.birthdate) {
        data.birthdate = new Date(data.birthdate);
    }
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    data.champions = data.champions.map((item: any) => {
        item.createdAt = new Date(item.createdAt);
        item.updatedAt = new Date(item.updatedAt);
        return item;
    });
    return data;
};

const highlanderPlayersSchemaResponseTransformer = (data: any) => {
    data = data.map((item: any) => highlanderPlayerSchemaResponseTransformer(item));
    return data;
};

export const leaguesResponseTransformer = async (data: any): Promise<LeaguesResponse> => {
    // return highlanderLeagueSchemaResponseTransformer(item);
    if (data.highlanderTournaments) {
        data.highlanderTournaments = highlanderTournamentsSchemaResponseTransformer(data.highlanderTournaments);
    }
    if (data.teams) {
        data.teams = highlanderTeamsSchemaResponseTransformer(data.teams);
    }
    if (data.players) {
        data.players = highlanderPlayersSchemaResponseTransformer(data.players);
    }
    return data;
};

export const scheduleItemsResponseTransformer = async (data: any): Promise<ScheduleItemsResponse> => {
    if (data.highlanderTournaments) {
        data.highlanderTournaments = highlanderTournamentsSchemaResponseTransformer(data.highlanderTournaments);
    }
    if (data.teams) {
        data.teams = highlanderTeamsSchemaResponseTransformer(data.teams);
    }
    if (data.players) {
        data.players = highlanderPlayersSchemaResponseTransformer(data.players);
    }
    return data;
};

export const teamsResponseTransformer = async (data: any): Promise<TeamsResponse> => {
    data.players = data.players.map((item: any) => highlanderPlayerSchemaResponseTransformer(item));
    data.highlanderTournaments = highlanderTournamentsSchemaResponseTransformer(data.highlanderTournaments);
    if (data.teamStatsHistories) {
        data.teamStatsHistories = data.teamStatsHistories.map((item: any) => {
            item.timestamp = BigInt(item.timestamp.toString());
            return item;
        });
    }
    data.teams = highlanderTeamsSchemaResponseTransformer(data.teams);
    return data;
};

const baseScheduleItemSchemaResponseTransformer = (data: any) => {
    data.scheduledTime = new Date(data.scheduledTime);
    return data;
};

const matchScheduleItemSchemaResponseTransformer = (data: any) => {
    data = baseScheduleItemSchemaResponseTransformer(data);
    return data;
};

export const playersResponseTransformer = async (data: any): Promise<PlayersResponse> => {
    // return highlanderPlayerSchemaResponseTransformer(item);
    data.highlanderTournaments = data.highlanderTournaments.map((item: any) => highlanderTournamentSchemaResponseTransformer(item));
    data.scheduleItems = data.scheduleItems.map((item: any) => matchScheduleItemSchemaResponseTransformer(item));
    data.teams = data.teams.map((item: any) => highlanderTeamSchemaResponseTransformer(item));
    if (data.playerStatsHistories) {
        data.playerStatsHistories = data.playerStatsHistories.map((item: any) => {
            item.timestamp = BigInt(item.timestamp.toString());
            return item;
        });
    }
    return data;
};
