// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://raw.githubusercontent.com' | 'https://esports-api.lolesports.com/persisted/gw' | 'https://prod-relapi.ewp.gg/persisted/gw' | 'https://esports-api.lolesports.com/persisted/gw' | 'https://prod-relapi.ewp.gg/persisted/gw' | 'https://esports-api.lolesports.com/persisted/gw' | 'https://prod-relapi.ewp.gg/persisted/gw' | 'https://esports-api.lolesports.com/persisted/gw' | 'https://prod-relapi.ewp.gg/persisted/gw' | 'https://esports-api.lolesports.com/persisted/gw' | 'https://prod-relapi.ewp.gg/persisted/gw' | 'https://esports-api.lolesports.com/persisted/gw' | 'https://prod-relapi.ewp.gg/persisted/gw' | 'https://esports-api.lolesports.com/persisted/gw' | 'https://prod-relapi.ewp.gg/persisted/gw' | 'https://esports-api.lolesports.com/persisted/gw' | 'https://prod-relapi.ewp.gg/persisted/gw' | 'https://esports-api.lolesports.com/persisted/gw' | 'https://prod-relapi.ewp.gg/persisted/gw' | 'https://feed.lolesports.com/livestats/v1' | 'https://feed.lolesports.com/livestats/v1' | 'https://api.lolesports.com/api/v1' | 'https://api.lolesports.com/api/v2' | 'https://api.lolesports.com/api/v2' | 'https://api.lolesports.com/api/v1' | 'https://api.lolesports.com/api/v1' | 'https://api.lolesports.com/api/v1' | 'https://api.lolesports.com/api/v1' | (string & {});
};

/**
 * Base 64 encoded string used to determine the
 * next "page" of data to pull
 *
 */
export type PageToken = string | null;

export type BaseLeague = {
    /**
     * The name of the league
     */
    name: string;
    /**
     * URL friendly version of the league's name
     */
    slug: string;
};

export type SimpleLeague = BaseLeague & {
    /**
     * The league's ID
     */
    id: string;
    /**
     * URL to an image of the League's logo
     */
    image: string;
};

export type ExtendedLeague = SimpleLeague & {
    /**
     * Unknown
     */
    priority: number;
};

export type HighlanderLeague = BaseLeague & {
    /**
     * The league's ID
     */
    id: number;
    /**
     * The [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier) for the league.
     *
     */
    guid: string;
    region: string;
    drupalId: number | null;
    logoUrl: string;
    /**
     * The date and time when this entry was created.
     */
    createdAt: Date;
    /**
     * The date and time when this entry was last updated.
     */
    updatedAt: Date;
    /**
     * Contains a description of the league translated in various languages.
     *
     * The keys are presented in the format ([ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1)
     * and [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2))
     *
     * `{languageCode}_{countryCode}`
     *
     * The value is a string containing
     * html tags representing the description in that specific locale.
     *
     */
    abouts: {
        [key: string]: string;
    };
    /**
     * Contains the names of the league translated in various languages.
     *
     * The keys are presented in the format ([ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1)
     * and [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2))
     *
     * `{languageCode}_{countryCode}`
     *
     * The value is a string containing
     * the name of the league in that specific locale.
     *
     */
    names: {
        [key: string]: string;
    };
    /**
     * An array containing the [UUIDs](https://en.wikipedia.org/wiki/Universally_unique_identifier)
     * for the tournaments in this league.
     *
     */
    tournaments?: Array<string>;
};

/**
 * Describes the amount of wins and losses the team has incurred
 * in a particular stage of the tournament specifically group stage
 *
 * For knockout phase, each series is treated individually.
 *
 * This object is null when the match is ongoing and it is in the
 * knockout stage.
 *
 */
export type Record = {
    losses: number;
    wins: number;
} | null;

export type Result = {
    /**
     * The number of games the team has won in that
     * in the series
     *
     */
    gameWins: number;
};

/**
 * Indicate whether the team won or lost the series
 *
 * This will be null if the match is ongoing
 *
 */
export const Outcome = { LOSS: 'loss', WIN: 'win' } as const;

/**
 * Indicate whether the team won or lost the series
 *
 * This will be null if the match is ongoing
 *
 */
export type Outcome = typeof Outcome[keyof typeof Outcome];

export type Team = {
    code: string;
    image: string;
    name: string;
};

export type CustomTeam = {
    id: TeamId;
    side: 'blue' | 'red';
};

export type ExtendedTeam = Team & {
    id: TeamId;
    slug: TeamSlug;
    alternativeImage: string;
    homeLeague: HomeLeague;
    players: Array<Player>;
};

export type HomeLeague = {
    /**
     * The name of the league
     */
    name: string;
    /**
     * The region where the league is located
     */
    region: string;
};

/**
 * The URL friendly version of the team name
 */
export type TeamSlug = string;

/**
 * The team id
 */
export type TeamId = string;

export type BaseStrategy = {
    count: 1 | 3 | 5;
};

export type Strategy = BaseStrategy & {
    type: 'bestOf';
};

export type Teams = [
    Team,
    Team
];

export type BaseMatch = {
    teams: Teams;
};

export type SimpleMatch = BaseMatch & {
    /**
     * The match id
     */
    id: string;
};

export const State = {
    COMPLETED: 'completed',
    UNSTARTED: 'unstarted',
    IN_PROGRESS: 'inProgress'
} as const;

export type State = typeof State[keyof typeof State];

export const EventType = { MATCH: 'match', SHOW: 'show' } as const;

export type EventType = typeof EventType[keyof typeof EventType];

export type BaseEvent = {
    match?: BaseMatch;
};

export type SimpleEvent = {
    /**
     * The time the match started
     */
    startTime: Date;
    blockName: string | null;
    match: SimpleMatch & {
        strategy: Strategy;
        teams: Array<{
            result: Result;
        }>;
    };
};

export type ExtendedEvent = SimpleEvent & {
    state: State;
    type: EventType;
};

export type Tournament = {
    /**
     * The date the tournament ends/ended.
     */
    endDate: string;
    /**
     * This is the tournament id
     */
    id: string;
    slug: string;
    /**
     * The date the tournament starts/started.
     */
    startDate: string;
};

/**
 * Represents a stage in a tournament.
 *
 * Whether it is the group or knockout stage.
 *
 */
export type Stage = {
    /**
     * The name of that stage of the tournament
     */
    name: string;
    /**
     * The type of the stage.
     */
    type: 'groups' | 'bracket';
    slug: string;
    /**
     * Each object in the array represents a particular round in that
     * specific stage in the tournament.
     *
     * For the knockout stages, we could have the quarter finals,
     * semi finals and the finals under their own sections.
     *
     * For the group stage, there is usually only one section.
     *
     */
    sections: Array<Section>;
};

export type Section = {
    /**
     * The name of the section
     */
    name: string;
    matches: Array<SimpleMatch & {
        state: State;
        /**
         * This stores the previous match ids for the teams in the current
         * match were involved in.
         *
         * For group stages this is usually null. For bracket stage it is
         * used to indicate the matches that were played before the match
         * in question.
         *
         */
        previousMatchIds: Array<string> | null;
        /**
         * The purpose of this key is unknown. So far the only value it
         * has seems to be null.
         *
         */
        flags: string | null;
        teams: Array<{
            id: TeamId;
            slug: TeamSlug;
            result: Result & {
                outcome: Outcome;
            };
        }>;
    }>;
    /**
     * Contains details about the actual standings for that particular
     * section
     *
     * This is mostly used for the group stage. For the knockout stages, it
     * is usually empty.
     *
     */
    rankings: Array<Ranking>;
};

export type Ranking = {
    /**
     * The league position
     */
    ordinal: number;
    /**
     * The teams that are at that league position.
     *
     * In most cases there will only be one team object in this array. In
     * cases where several teams are tied with the same score, this array will
     * contain all teams tied for that position.
     *
     */
    teams: Array<Team & {
        id?: TeamId;
        slug?: TeamSlug;
        record?: Record;
    }>;
};

export type Game = {
    vods: Array<Vod>;
};

export type SimpleGame = {
    /**
     * The game ID
     */
    id: string;
    state: State;
    /**
     * The number of the game
     */
    number: 1 | 2 | 3 | 4 | 5;
    vods: Array<ExtendedVod>;
};

export type ExtendedGame = SimpleGame & {
    teams: Array<CustomTeam>;
};

export type Vod = {
    parameter: string;
};

export type ExtendedVod = Vod & {
    locale: Locale;
    /**
     * The platform that is hosting the vod
     *
     */
    provider: 'youtube' | 'twitch';
    /**
     * Purpose Unknown
     */
    offset: number;
};

/**
 * This is the locale or language code using [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1)
 * and [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)
 *
 */
export const Locale = {
    EN_US: 'en-US',
    EN_GB: 'en-GB',
    EN_AU: 'en-AU',
    CS_CZ: 'cs-CZ',
    DE_DE: 'de-DE',
    EL_GR: 'el-GR',
    ES_ES: 'es-ES',
    ES_MX: 'es-MX',
    FR_FR: 'fr-FR',
    HU_HU: 'hu-HU',
    IT_IT: 'it-IT',
    PL_PL: 'pl-PL',
    PT_BR: 'pt-BR',
    RO_RO: 'ro-RO',
    RU_RU: 'ru-RU',
    TR_TR: 'tr-TR',
    JA_JP: 'ja-JP',
    KO_KR: 'ko-KR'
} as const;

/**
 * This is the locale or language code using [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1)
 * and [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)
 *
 */
export type Locale = typeof Locale[keyof typeof Locale];

export type Player = {
    id: string;
    summonerName: string;
    firstName: string;
    lastName: string;
    image: string;
    role: string;
};

export type Window = {
    /**
     * The game Id of the match
     */
    esportsGameId: string;
    /**
     * The match Id of the match
     */
    esportsMatchId: string;
    gameMetadata: GameMetadata;
    frames: Array<WindowFrame>;
};

export type GameMetadata = {
    /**
     * The patch the match was played on
     */
    patchVersion: string;
    blueTeamMetadata: TeamMetadata;
    redTeamMetadata: TeamMetadata;
};

export type TeamMetadata = {
    /**
     * The team Id
     */
    esportsTeamId: string;
    participantMetadata: Array<ParticipantMetadata | ParticipantMetadataExtended>;
};

export type ParticipantMetadata = {
    participantId: ParticipantId;
    summonerName: string;
    championId: string;
    role: 'top' | 'jungle' | 'mid' | 'bottom' | 'support';
};

export type ParticipantMetadataExtended = ParticipantMetadata & {
    esportsPlayerId: string;
};

export const ParticipantId = {
    1: 1,
    2: 2,
    3: 3,
    4: 4,
    5: 5,
    6: 6,
    7: 7,
    8: 8,
    9: 9,
    10: 10
} as const;

export type ParticipantId = typeof ParticipantId[keyof typeof ParticipantId];

export type BaseFrame = {
    rfc460Timestamp: Date;
};

export type WindowFrame = BaseFrame & {
    rfc460Timestamp: Date;
    gameState: 'in_game' | 'finished';
    blueTeam: TeamStats;
    redTeam: TeamStats;
};

export type DetailsFrame = BaseFrame & {
    participants: Array<ExtendedParticipantStats>;
};

export type TeamStats = {
    totalGold: number;
    inhibitors: number;
    towers: number;
    barons: number;
    totalKills: number;
    dragons: Array<'ocean' | 'mountain' | 'infernal' | 'cloud' | 'elder'>;
    participants: Array<ParticipantStats>;
};

export type BaseParticipantStats = {
    participantId: ParticipantId;
    level: number;
    kills: number;
    deaths: number;
    assists: number;
    creepScore: number;
};

export type ParticipantStats = BaseParticipantStats & {
    totalGold: number;
    currentHealth: number;
    maxHealth: number;
};

export type ExtendedParticipantStats = ParticipantStats & {
    totalGoldEarned: number;
    killParticipation: number;
    championDamageShare: number;
    wardsPlaced: number;
    wardsDestroyed: number;
    attackDamage: number;
    abilityPower: number;
    criticalChance: number;
    attackSpeed: number;
    lifeSteal: number;
    armor: number;
    magicResistance: number;
    tenacity: number;
    /**
     * Contains the item Ids of the items in the inventory
     *
     */
    items: Array<number>;
    perkMetadata: PerkMetadata;
    abilities: Abilities;
};

export type PerkMetadata = {
    /**
     * The id of the primary rune path
     *
     */
    styleId: 8000 | 8100 | 8200 | 8300 | 8400;
    /**
     * The id of the secondary rune path
     *
     */
    subStyleId: 8000 | 8100 | 8200 | 8300 | 8400;
    /**
     * The runes selected.
     *
     * Index 0 - 3 are the ids of the primary runes
     * Index 4 - 5 are the ids of the secondary runes
     * Index 6 - 8 are the ids of the stats shard
     *
     */
    perks: [
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number
    ];
};

/**
 * Contains the abilities the summoner levelled up at each level
 *
 */
export const Abilities = {
    Q: 'Q',
    W: 'W',
    E: 'E',
    R: 'R'
} as const;

/**
 * Contains the abilities the summoner levelled up at each level
 *
 */
export type Abilities = typeof Abilities[keyof typeof Abilities];

export type NavItem = {
    id: number;
    link: string;
    slug: string | null;
    label: string;
    imageUrl: string | null;
    order: number;
    external: boolean;
    parentNavItem: NavItem & ({
        [key: string]: unknown;
    } | null);
    /**
     * The date and time when this entry was created.
     */
    createdAt: Date;
    /**
     * The date and time when this entry was last updated.
     */
    updatedAt: Date;
};

export type Video = {
    id: number;
    slug: string | null;
    label: string | null;
    /**
     * The video's locale. The value is a [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1)
     * language code.
     *
     */
    locale: string;
    /**
     * Contains the tournament Id and the game Id of that match.
     *
     */
    reference: string;
    /**
     * URL to the YouTube video of the match
     *
     */
    source: string;
    /**
     * The date and time when this entry was created.
     */
    createdAt: Date;
    /**
     * The date and time when this entry was last updated.
     */
    updatedAt: Date;
    game: GameId;
};

/**
 * The game Id of the match.
 *
 * It is a [UUID version 4](https://en.wikipedia.org/wiki/Universally_unique_identifier)
 *
 */
export type GameId = string;

export type HighlanderTournaments = Array<HighlanderTournament>;

export type HighlanderTournament = {
    /**
     * The tournament Id
     *
     * It is a [UUID version 4](https://en.wikipedia.org/wiki/Universally_unique_identifier)
     *
     */
    id: string;
    /**
     * URL friendly version of the tournament name
     */
    title: string;
    /**
     * The tournament's name
     */
    description: string;
    /**
     * The integer in the string represents the league ID.
     */
    leagueReference: string;
    roles: Roles;
    bracketType?: BracketType;
    matchType?: MatchType;
    rosteringStrategy?: RosteringStrategy;
    seedingStrategy?: RosteringStrategy;
    queues: {
        [key: string]: unknown;
    };
    /**
     * The keys to this object are [UUID version 4](https://en.wikipedia.org/wiki/Universally_unique_identifier)
     * representing the roster ID.
     *
     * Their values are objects but they don't contain anything useful about the roster.
     *
     */
    rosters: {
        [key: string]: {
            /**
             * The roster ID.
             *
             * It is a [UUID version 4](https://en.wikipedia.org/wiki/Universally_unique_identifier)
             *
             */
            id: string;
            state?: 'eliminated';
            /**
             * The abbreviated version of the team's name.
             */
            name: string;
            roles: {
                [key: string]: unknown;
            };
            teamReference: string;
            substitutions: {
                [key: string]: unknown;
            };
            /**
             * The Team ID
             */
            team: string;
        };
    };
    /**
     * If the value is true then the league/tournament has concluded, otherwise it is ongoing.
     *
     */
    published: true | false;
    breakpoints?: Breakpoints;
    brackets: Brackets;
    standings?: Standings;
    /**
     * The array contains [UUID version 4](https://en.wikipedia.org/wiki/Universally_unique_identifier) Match IDs
     *
     * Despite the name of this property it is unreliable as for some tournaments this array will
     * contain match IDs yet the matches are over.
     *
     */
    liveMatches: Array<string>;
    /**
     * The day the tournament starts/started.
     */
    startDate: Date;
    /**
     * The day the tournament ends/ended.
     */
    endDate: Date;
    /**
     * Contains all the platform IDs in for this tournaments.
     *
     * A platform ID is combination of the gameRealm and the gameId.
     * The regex below describes the format.
     *
     * `^[A-Z]+\d+:\d+$`
     *
     */
    platformIds: Array<string>;
    /**
     * 'Contains all the gameIds in this tournament.
     *
     * **Note:** The gameIds are in the format [UUID version 4](https://en.wikipedia.org/wiki/Universally_unique_identifier)'
     *
     */
    gameIds: Array<string>;
    /**
     * The league ID
     */
    leagueId: string;
    /**
     * The league ID
     */
    league: string;
};

export type RosteringStrategy = {
    identifier: 'passthru' | 'random';
};

export type Roles = {
    creator: Array<Role>;
    owner: Array<Role>;
};

export type Role = {
    origin: 'BEARER_TOKEN';
    region: 'global';
    summonerName: 'test-user';
    summonerLevel: 0;
    profileIconId: 0;
    admin: true;
};

export type SimpleRoster = {
    /**
     * The roster ID
     */
    roster?: string;
};

/**
 * The keys to this object are [UUID version 4](https://en.wikipedia.org/wiki/Universally_unique_identifier)
 * representing the roster ID.
 *
 */
export type Breakpoints = {
    [key: string]: {
        /**
         * The breakpoint's ID
         */
        id: string;
        name: string;
        position: number;
        input: Array<SimpleRoster & {
            /**
             * The bracket ID
             */
            bracket?: string;
            standing?: number;
        }>;
        standings?: Standings;
        scores: Scores;
        roles: Roles;
        generator: {
            identifier?: 'noop';
        };
    };
};

export type Standings = {
    result: HighlanderResult;
    /**
     * Unix timestamp in milliseconds of when the match started.
     */
    timestamp: bigint;
    /**
     * How the record was created/updated.
     */
    source?: 'manual' | 'bestOf';
    note?: string;
    history?: Array<Standings>;
    /**
     * If the value is true then the league/tournament has concluded, otherwise it is ongoing.
     *
     */
    closed: true | false;
};

export type HighlanderResult = Array<Array<SimpleRoster>>;

/**
 * The keys to this object are [UUID version 4](https://en.wikipedia.org/wiki/Universally_unique_identifier)
 * representing the bracket ID.
 *
 */
export type Brackets = {
    [key: string]: {
        /**
         * The bracket ID.
         */
        id: string;
        /**
         * The name of the bracket
         */
        name: string;
        position: number;
        groupPosition: number;
        groupName?: string;
        canManufacture: boolean;
        /**
         * Whether it is ongoing or completed.
         *
         * This is unreliable since some tournaments have the state unresolved yet they concluded
         * a long time ago.
         *
         */
        state: 'resolved' | 'unresolved' | 'unlinked';
        bracketType?: BracketType;
        matchType?: MatchType;
        gameMode?: GameMode;
        input?: Array<SimpleRoster & {
            /**
             * The breakpoint ID
             */
            breakpoint?: string;
            standing?: number;
        }>;
        /**
         * The keys to this object are [UUID version 4](https://en.wikipedia.org/wiki/Universally_unique_identifier)
         * representing the match ID.
         *
         */
        matches: {
            [key: string]: HighlanderMatch;
        };
        standings?: Standings;
        inheritableMatchScoringStrategy?: Scoring;
        roles: Roles;
        scoring?: Scoring;
        scores: Scores;
        matchScoring?: Scoring;
        matchScores: Scores;
    };
};

export type BracketType = {
    identifier: 'round_robin' | 'single_elim' | 'gauntlet' | 'bestOf';
    options?: {
        rounds: string;
    };
};

export type MatchType = {
    identifier: 'bestOf' | 'single_elim';
    options?: {
        best_of: string;
    };
};

export type GameMode = {
    identifier: 'lol:duel' | 'lol:classic';
    requiredPlayers: 1 | 5;
    mapName: 'summoner_rift' | 'howling_abyss';
};

export type HighlanderMatch = {
    /**
     * The match ID
     */
    id: string;
    name: string;
    position: number;
    /**
     * Whether it is ongoing or completed.
     *
     */
    state: unknown;
    groupPosition: number;
    matchType?: MatchType;
    gameMode?: GameMode;
    input: Array<SimpleRoster & ({
        /**
         * The match ID
         */
        match?: string;
    } | {
        /**
         * The breakpoint ID
         */
        breakpoint?: string;
    }) & {
        standing?: number;
    }>;
    /**
     * The keys to this object are [UUID version 4](https://en.wikipedia.org/wiki/Universally_unique_identifier)
     * representing the game ID.
     *
     * These are the games played in that series.
     *
     * The number of properties(key and value pair) in this object will be equal to the type of series that was
     * played. For a best of 1 there will be only 1 game, 3 for best of 3s and 5 for best of 5s.
     *
     */
    games: {
        [key: string]: HighlanderGame;
    };
    standings?: Standings;
    tiebreaker: true | false;
    remadeGames: Array<HighlanderGame>;
    roles: Roles;
    scoring?: Scoring;
    scores: Scores;
};

export type HighlanderGame = {
    id: GameId;
    name: string;
    generatedName: string;
    state?: 'remade';
    gameMode?: GameMode;
    input: Array<SimpleRoster & ({
        /**
         * The match ID
         */
        match?: string;
    } | {
        /**
         * The breakpoint ID
         */
        breakpoint?: string;
    }) & {
        standing?: number;
    }>;
    standings?: Standings;
    scores: Scores;
    /**
     * The numeric version of the game ID
     *
     * This is what is used to access the ACS endpoint.
     *
     */
    gameId?: string;
    /**
     * The ID of the tournament realm on which the game was played on
     *
     */
    gameRealm?: string;
    /**
     * A combination of the gameRealm and the gameId
     */
    platformId?: string;
    revision: number;
    roles: Roles;
};

export type Scoring = {
    /**
     * **Note:** The `LegacyScoringStrategy` value has only been found in the 2015 worlds championship.
     */
    identifier: 'standard' | 'LegacyScoringStrategy';
    options: {
        points: [
            number,
            number
        ];
    };
};

/**
 * The keys to this object are [UUID version 4](https://en.wikipedia.org/wiki/Universally_unique_identifier)
 * representing the roster ID.
 *
 */
export type Scores = {
    [key: string]: number;
};

export type HighlanderRecords = Array<HighlanderRecord>;

export type HighlanderRecord = {
    wins: number;
    losses: number;
    ties: number;
    score: number;
    /**
     * The roster's [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier)
     */
    roster: string;
    /**
     * The tournament's [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier)
     */
    tournament: unknown;
    /**
     * The bracket's [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier)
     */
    bracket: unknown;
    /**
     * A combination of the bracket and roster UUIDs. The two are separated by a colon\
     *
     */
    id: string;
};

export type HighlanderTeam = {
    /**
     * The team ID.
     */
    id: number;
    /**
     * URL friendly version of the team name.
     */
    slug: string;
    /**
     * The team name.
     */
    name: string;
    /**
     * The team's [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier).
     */
    guid: string;
    teamPhotoUrl: string | null;
    /**
     * URL to an image of the team's logo.
     */
    logoUrl: string;
    /**
     * The acronym form of the team name
     */
    acronym: string;
    /**
     * Describes the league this team participates in during the regular seasons.
     *
     */
    homeLeague: string;
    /**
     * Alternative URL to the team's logo.
     */
    altLogoUrl: string | null;
    /**
     * The date and time when this entry was created.
     */
    createdAt: Date;
    /**
     * The date and time when this entry was last updated.
     */
    updatedAt: Date;
    /**
     * Contains a description of the team translated to various languages.
     *
     * The keys are presented in the format ([ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1)
     * and [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2))
     *
     * `{languageCode}_{countryCode}`
     *
     * The value is a string containing
     * html tags representing the description in that specific locale.
     *
     */
    bios: {
        [key: string]: string;
    };
    foreignIds: ForeignIds;
    /**
     * An array containing the player IDs for those belonging in that team.
     */
    players: Array<number>;
    /**
     * An array of the player IDs of those in the main roster
     */
    starters: Array<number>;
    /**
     * An array of the player IDs of the subs.
     */
    subs: Array<number>;
};

export type ForeignIds = {
    drupalId?: string;
};

export type HighlanderPlayer = {
    /**
     * The player ID
     */
    id: number;
    /**
     * URL friendly version of the player's in game name
     */
    slug: string;
    /**
     * The player's in game name
     */
    name: string;
    firstName: string;
    LastName?: string | null;
    /**
     * The role they usually play
     */
    roleSlug: string;
    /**
     * URL to the player's photo
     */
    photoUrl: string | null;
    hometown: string | null;
    region: string;
    birthdate: Date | null;
    /**
     * The date and time when this entry was created.
     */
    createdAt: Date;
    /**
     * The date and time when this entry was last updated.
     */
    updatedAt: Date;
    /**
     * Contains a description of the player translated to various languages.
     *
     * The keys are presented in the format ([ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1)
     * and [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2))
     *
     * `{languageCode}_{countryCode}`
     *
     * The value is a string containing
     * html tags representing the description in that specific locale.
     *
     */
    bios: {
        [key: string]: string;
    };
    foreignIds: ForeignIds & {
        [key: string]: string;
    };
    /**
     * Contains links to the player's social media accounts.
     *
     * The key is the name of the social media platform and the value is the URL
     *
     */
    socialNetworks: {
        [key: string]: string;
    };
    champions: Array<{
        id: number;
        /**
         * The player ID
         */
        playerId: number;
        /**
         * The champion ID
         */
        championId: number;
        /**
         * The champion's name
         */
        championKey: string;
        /**
         * The champion's name
         */
        championName: string;
        /**
         * The date and time when this entry was created.
         */
        createdAt: Date;
        /**
         * The date and time when this entry was last updated.
         */
        updatedAt: Date;
    }>;
};

/**
 * An array containing the teams that have participated in this league.
 *
 */
export type HighlanderTeams = Array<HighlanderTeam>;

export type HighlanderPlayers = Array<HighlanderPlayer>;

export type BaseScheduleItem = {
    /**
     * The schedule item ID.
     */
    id: string;
    /**
     * The time the match/event is/was scheduled to start.
     */
    scheduledTime: Date;
    tags: Tags;
    /**
     * The tournament ID
     */
    tournament: string;
    /**
     * The League ID
     */
    league: string;
};

export type MatchScheduleItem = BaseScheduleItem & {
    /**
     * Contains the tournament and match Ids for the specific match.
     *
     */
    content: string;
    /**
     * The match ID
     */
    match: string;
    /**
     * The bracket ID
     */
    bracket: string;
};

export type EventScheduleItem = BaseScheduleItem & {
    content: string;
};

export type ScheduleItem = MatchScheduleItem | EventScheduleItem;

/**
 * The labels are used to describe the week and day the match/event is taking place in.
 * Also, it could indicate the stage of the tournament.
 *
 * The blockPrefix comes before the block Label. Same with the subBlockPrefix and the subBlockLabel.
 *
 */
export type Tags = {
    subBlockLabel: string;
    blockLabel: string;
    leagueLabel: string;
    blockPrefix?: string;
    subBlockPrefix: string;
    yearLabel?: string;
    /**
     * Contains the tournament and bracket Ids the match/event belongs to.
     *
     */
    stageLabel?: string;
    /**
     * Contains the tournament ID.
     *
     */
    tournamentLabel: string;
};

export type Hl = Locale;

/**
 * The id(s) of the league(s) you want details of
 *
 */
export type LeagueIds = Array<bigint>;

/**
 * The id of the league you want details of
 *
 */
export type LeagueId = bigint;

/**
 * The id of the league you want details of
 */
export type HighlanderLeagueId = number;

/**
 * Base 64 encoded string used to determine the
 * next "page" of data to pull
 *
 */
export type PageToken2 = string;

/**
 * The id(s) of the tournament(s) you want details ofs
 *
 */
export type TournamentIds = Array<bigint>;

/**
 * The id of the match that you want
 *
 */
export type Id = bigint;

/**
 * The team slug(s).
 *
 * You can input more than one slug.
 *
 */
export type TeamSlugs = Array<string>;

/**
 * The game Id(s).
 *
 * You can input more than one game Id(s).
 *
 */
export type GameIds = Array<bigint>;

/**
 * The game id of the match
 *
 */
export type PathGameId = bigint;

/**
 * The date-time (RFC3339)
 *
 */
export type StartingTime = Date;

/**
 * The id of the league you want details of
 */
export type League = string;

/**
 * The team slug.
 */
export type TeamSlug2 = string;

/**
 * The tournament ID.
 */
export type HighlanderTournamentId = string;

/**
 * The player slug.
 */
export type PlayerSlug = string;

export type GetLeaguesData = {
    body?: never;
    path?: never;
    query: {
        hl: Locale;
    };
    url: '/getLeagues';
};

export type GetLeaguesResponses = {
    /**
     * Successful request
     */
    200: {
        data: {
            leagues: Array<ExtendedLeague & {
                /**
                 * Indicates which type of tournament the league is. Whether
                 * international or a regional tournament. The region name is
                 * given.
                 *
                 */
                region: string;
            }>;
        };
    };
};

export type GetLeaguesResponse = GetLeaguesResponses[keyof GetLeaguesResponses];

export type GetScheduleData = {
    body?: never;
    path?: never;
    query: {
        hl: Locale;
        /**
         * The id(s) of the league(s) you want details of
         *
         */
        leagueId?: Array<bigint>;
        /**
         * Base 64 encoded string used to determine the
         * next "page" of data to pull
         *
         */
        pageToken?: string;
    };
    url: '/getSchedule';
};

export type GetScheduleResponses = {
    /**
     * Successful request
     */
    200: {
        data: {
            schedule: {
                /**
                 * The time the data presented was last updated
                 */
                updated: Date;
                pages: {
                    older: PageToken;
                    newer: PageToken;
                };
                events: Array<ExtendedEvent & {
                    league: BaseLeague;
                    match: {
                        teams: Array<{
                            record: Record;
                            result: {
                                outcome: Outcome;
                            };
                        }>;
                    };
                }>;
            };
        };
    };
};

export type GetScheduleResponse = GetScheduleResponses[keyof GetScheduleResponses];

export type GetLiveData = {
    body?: never;
    path?: never;
    query: {
        hl: Locale;
    };
    url: '/getLive';
};

export type GetLiveResponses = {
    /**
     * Successful request
     */
    200: {
        data: {
            schedule: {
                /**
                 * Array of event objects representing matches that are
                 * currently ongoing.
                 *
                 * This will be null if no match is taking place at that
                 * time
                 *
                 */
                events: Array<ExtendedEvent & {
                    id: string;
                    league: ExtendedLeague;
                    match?: {
                        teams: Array<{
                            slug: TeamSlug;
                            record: Record;
                            result: {
                                outcome: Outcome;
                            };
                        }>;
                    };
                }> | null;
            };
        };
    };
};

export type GetLiveResponse = GetLiveResponses[keyof GetLiveResponses];

export type GetTournamentsForLeagueData = {
    body?: never;
    path?: never;
    query: {
        hl: Locale;
        /**
         * The id of the league you want details of
         *
         */
        leagueId?: bigint;
    };
    url: '/getTournamentsForLeague';
};

export type GetTournamentsForLeagueResponses = {
    /**
     * Successful request
     */
    200: {
        data: {
            /**
             * An array of league object(s) where each object contains an array of
             * tournaments.
             *
             */
            leagues: Array<{
                /**
                 * An array of tournament object(s) where each object describes a
                 * specific tournament.
                 *
                 */
                tournaments: Array<Tournament>;
            }>;
        };
    };
};

export type GetTournamentsForLeagueResponse = GetTournamentsForLeagueResponses[keyof GetTournamentsForLeagueResponses];

export type GetStandingsData = {
    body?: never;
    path?: never;
    query: {
        hl: Locale;
        /**
         * The id(s) of the tournament(s) you want details ofs
         *
         */
        tournamentId?: Array<bigint>;
    };
    url: '/getStandings';
};

export type GetStandingsResponses = {
    /**
     * Successful request
     */
    200: {
        data: {
            /**
             * Each object in the array contains details of each tournament requested.
             *
             */
            standings: Array<{
                stages: Array<Stage>;
            }>;
        };
    };
};

export type GetStandingsResponse = GetStandingsResponses[keyof GetStandingsResponses];

export type GetCompletedEventsData = {
    body?: never;
    path?: never;
    query: {
        hl: Locale;
        /**
         * The id(s) of the tournament(s) you want details ofs
         *
         */
        tournamentId?: Array<bigint>;
    };
    url: '/getCompletedEvents';
};

export type GetCompletedEventsResponses = {
    /**
     * Successful request
     */
    200: {
        data: {
            schedule: {
                events: Array<SimpleEvent & {
                    games: Array<Game>;
                    match: {
                        type: 'normal';
                    };
                }>;
            };
        };
    };
};

export type GetCompletedEventsResponse = GetCompletedEventsResponses[keyof GetCompletedEventsResponses];

export type GetEventDetailsData = {
    body?: never;
    path?: never;
    query: {
        hl: Locale;
        /**
         * The id of the match that you want
         *
         */
        id: bigint;
    };
    url: '/getEventDetails';
};

export type GetEventDetailsResponses = {
    /**
     * Succesful request
     */
    200: {
        data: {
            event: BaseEvent & {
                id: string;
                type: EventType;
                league: SimpleLeague;
                match: {
                    games: Array<ExtendedGame>;
                    strategy: BaseStrategy;
                    teams: [
                        {
                            id: TeamId;
                            result: Result;
                        },
                        {
                            id: TeamId;
                            result: Result;
                        }
                    ];
                };
                /**
                 * For a live match this will contain information about various streams,
                 * the platforms they are on and the locale.
                 *
                 * Otherwise it will be null.
                 *
                 */
                streams: Array<ExtendedVod> | null;
            };
        };
    };
};

export type GetEventDetailsResponse = GetEventDetailsResponses[keyof GetEventDetailsResponses];

export type GetTeamsData = {
    body?: never;
    path?: never;
    query: {
        hl: Locale;
        /**
         * The team slug(s).
         *
         * You can input more than one slug.
         *
         */
        id?: Array<string>;
    };
    url: '/getTeams';
};

export type GetTeamsResponses = {
    /**
     * Successful request
     */
    200: {
        data: {
            teams: Array<ExtendedTeam>;
        };
    };
};

export type GetTeamsResponse = GetTeamsResponses[keyof GetTeamsResponses];

export type GetGamesData = {
    body?: never;
    path?: never;
    query: {
        hl: Locale;
        /**
         * The game Id(s).
         *
         * You can input more than one game Id(s).
         *
         */
        id?: Array<bigint>;
    };
    url: '/getGames';
};

export type GetGamesResponses = {
    /**
     * Successful request
     */
    200: {
        data: {
            games: Array<SimpleGame>;
        };
    };
};

export type GetGamesResponse = GetGamesResponses[keyof GetGamesResponses];

export type GetWindowData = {
    body?: never;
    path: {
        /**
         * The game id of the match
         *
         */
        gameId: bigint;
    };
    query?: {
        /**
         * The date-time (RFC3339)
         *
         */
        startingTime?: Date;
    };
    url: '/window/{gameId}';
};

export type GetWindowResponses = {
    /**
     * Successful request
     */
    200: Window;
};

export type GetWindowResponse = GetWindowResponses[keyof GetWindowResponses];

export type GetDetailsData = {
    body?: never;
    path: {
        /**
         * The game id of the match
         *
         */
        gameId: bigint;
    };
    query?: {
        /**
         * The date-time (RFC3339)
         *
         */
        startingTime?: Date;
        /**
         * A list of the participant Ids separated by underscores and not commas
         *
         */
        participantIds?: string;
    };
    url: '/details/{gameId}';
};

export type GetDetailsResponses = {
    /**
     * Successful request
     */
    200: {
        frames: Array<DetailsFrame>;
    };
};

export type GetDetailsResponse = GetDetailsResponses[keyof GetDetailsResponses];

export type NavItemsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/navItems';
};

export type NavItemsResponses = {
    /**
     * Successful request
     */
    200: {
        navItems: Array<NavItem>;
        leagues: Array<HighlanderLeague>;
    };
};

export type NavItemsResponse = NavItemsResponses[keyof NavItemsResponses];

export type VideosData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/videos';
};

export type VideosResponses = {
    /**
     * Successful request
     */
    200: {
        videos: Array<Video>;
    };
};

export type VideosResponse = VideosResponses[keyof VideosResponses];

export type HighlanderTournamentsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The id of the league you want details of
         */
        league: string;
    };
    url: '/highlanderTournaments';
};

export type HighlanderTournamentsErrors = {
    /**
     * Not Found
     */
    404: {
        error: {
            statusCode: 404;
            message: string;
        };
    };
};

export type HighlanderTournamentsError = HighlanderTournamentsErrors[keyof HighlanderTournamentsErrors];

export type HighlanderTournamentsResponses = {
    /**
     * Successful request
     */
    200: HighlanderTournaments;
};

export type HighlanderTournamentsResponse = HighlanderTournamentsResponses[keyof HighlanderTournamentsResponses];

export type LeaguesData = {
    body?: never;
    path?: never;
    query: {
        /**
         * 'This endpoint requires either the id or the slug to be passed. If both are present then only the first
         * one will be considered.
         *
         * _Due to a limitation in the OpenApi specification it is not possible to show the mutual exclusive nature
         * that the query parameters in this endpoint require. The schema below is as close as a representation I
         * could get in expressing the nature of the query parameters._
         *
         * Check the examples below to help better understand the query parameters needed.
         *
         * **Example 1**
         *
         * `https://api.lolesports.com/api/v1/leagues?id=3`
         *
         * This will return the details for **LEC**.
         *
         * **Example 2**
         *
         * `https://api.lolesports.com/api/v1/leagues?slug=worlds`
         *
         * This will return the details for **Worlds**
         *
         * **Example 3**
         *
         * `https://api.lolesports.com/api/v1/leagues?id=3&slug=worlds`
         *
         * In such a scenario where both query parameters are used only the first will be considered, hence it will
         * only return the details for **LEC**.
         *
         * **Example 4**
         *
         * `https://api.lolesports.com/api/v1/leagues`
         *
         * This is not valid. At least one of the two query parameters (id or slug) is required.'
         *
         */
        query: {
            id: number;
        } | {
            slug: string;
        };
    };
    url: '/leagues';
};

export type LeaguesErrors = {
    /**
     * Not Found
     */
    404: {
        error?: 'Invalid Input Error';
    };
};

export type LeaguesError = LeaguesErrors[keyof LeaguesErrors];

export type LeaguesResponses = {
    /**
     * Successful request
     */
    200: {
        /**
         * This array contains information about the league retrieved.
         *
         */
        leagues: [
            HighlanderLeague
        ];
        highlanderTournaments?: HighlanderTournaments;
        highlanderRecords?: HighlanderRecords;
        teams?: HighlanderTeams;
        players?: HighlanderPlayers;
    };
};

export type LeaguesResponse = LeaguesResponses[keyof LeaguesResponses];

export type ScheduleItemsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The id of the league you want details of
         */
        leagueId: number;
    };
    url: '/scheduleItems';
};

export type ScheduleItemsResponses = {
    /**
     * Successful request
     */
    200: {
        scheduleItems?: Array<ScheduleItem>;
        highlanderTournaments?: HighlanderTournaments;
        teams?: HighlanderTeams;
        highlanderRecords?: HighlanderRecords;
        players?: HighlanderPlayers;
    };
};

export type ScheduleItemsResponse = ScheduleItemsResponses[keyof ScheduleItemsResponses];

export type TeamsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The team slug.
         */
        slug: string;
        /**
         * The tournament ID.
         */
        tournament: string;
    };
    url: '/teams';
};

export type TeamsResponses = {
    /**
     * Successful request
     */
    200: {
        /**
         * Contains the players currently in the team.
         */
        players: Array<HighlanderPlayer & {
            teamRosterStat?: string;
        }>;
        highlanderTournaments: HighlanderTournaments;
        /**
         * Contains details about a few of the team's upcoming matches
         */
        scheduleItems: Array<ScheduleItem>;
        /**
         * Contains a summary of the team stats during that particular tournament.
         *
         */
        teamStatsSummaries?: [
            {
                /**
                 * Contains the team ID
                 */
                teamId: string;
                /**
                 * The team's KDA Ratio
                 */
                kdaRatio: number;
                /**
                 * The position the team ranks at compared to other teams' KDA ratio
                 *
                 */
                kdaRatioRank: number;
                /**
                 * The average length of the team's wins in seconds.
                 *
                 */
                averageWinLength: number;
                /**
                 * The position the team ranks at compared to other team's average win lengths.
                 *
                 */
                averageWinLengthRank: number;
                /**
                 * The ratio of first dragons killed by this team compared to the total first dragons killed
                 * in this team's matches.
                 *
                 */
                firstDragonKillRatio: number;
                /**
                 * The position the teams ranks at compared to other team's first dragon kill ratio
                 *
                 */
                firstDragonKillRatioRank: number;
                /**
                 * The ratio of first tower secured by this team compared to the total first towers secured
                 * in this team's matches.
                 *
                 */
                firstTowerRatio: number;
                /**
                 * The position the teams ranks at compared to other team's first tower ratio.
                 *
                 */
                firstTowerRatioRank: number;
                /**
                 * It is assumed that the values represent the damage dealt in thousands.
                 *
                 */
                averageDamageByPosition: {
                    DUO_CARRY?: number;
                    DUO_SUPPORT?: number;
                    SOLO?: number;
                    NONE?: number;
                    DUO?: number;
                };
            }
        ];
        /**
         * Contains stats of the players of the particular team who played in that tournament.
         *
         */
        teamRosterStats?: Array<{
            playerId: string;
            gamesPlayed: number;
            averageAssists: number;
            averageDeaths: number;
            averageKillParticipation: number;
            averageKills: number;
            summonerName: string;
            championIds: Array<number>;
        }>;
        /**
         * A contains stats of the team's previous 4 matches in that particular tournament.
         *
         */
        teamStatsHistories?: Array<{
            /**
             * Contains the game ID and the team ID.
             */
            id: string;
            /**
             * Unix timestamp in milliseconds of when the match started.
             */
            timestamp: bigint;
            assists: number;
            kills: number;
            win: true | false;
            championIds?: [
                number,
                number,
                number,
                number,
                number
            ];
            /**
             * The match ID
             */
            match: string;
            /**
             * The team ID
             */
            team: number;
            /**
             * The opponent's team ID
             */
            opponent: number;
            /**
             * The game ID
             */
            game: number;
        }>;
        teams: HighlanderTeams;
    };
};

export type TeamsResponse = TeamsResponses[keyof TeamsResponses];

export type PlayersData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The player slug.
         */
        slug: string;
        /**
         * The tournament ID.
         */
        tournament: string;
    };
    url: '/players';
};

export type PlayersResponses = {
    /**
     * Successful request
     */
    200: {
        /**
         * Contains information about the player in question.
         *
         * If `playerStatsSummary` and `playerStatsHistory` are missing then the player did not take part
         * in the tournament specificed by the tournament ID in the url.
         *
         */
        players: [
            HighlanderPlayer & {
                /**
                 * The IDs of the team(s) this player is/has been on the starting
                 * lineup
                 *
                 */
                starterOnTeams: Array<number>;
                /**
                 * The IDs of the team(s) this player is/has been on as a sub player
                 *
                 */
                subOnTeams: Array<number>;
                /**
                 * A combination of the teamIDs in `starterOnTeams` and `subOnTeams`
                 *
                 */
                teams: Array<number>;
                photoInformation: {
                    /**
                     * The width of the image in pixels.
                     */
                    width: number;
                    /**
                     * The height of the image in pixels.
                     */
                    height: number;
                    /**
                     * The image's file format.
                     */
                    type: string;
                    /**
                     * URL to the player's photo.
                     */
                    url: string;
                    transferred: number;
                    /**
                     * Size of the image in bytes
                     */
                    size: number;
                    time: number;
                };
                /**
                 * Contains the ids to schedule items representing the player's/team's next matches.
                 *
                 * This is regardless of the tournament ID passed in the url.
                 *
                 */
                scheduleItems: Array<string>;
                playerStatsSummary?: string;
                /**
                 * Contains the `playerStatsHistory` IDs, which are just the game ID of the match and the player
                 * ID separated by a colon.
                 *
                 * Contains the last 4 played matches in the specified tournament. The first ID is of the most
                 * recently played match.
                 *
                 */
                playerStatsHistory?: Array<string>;
            }
        ];
        /**
         * Contains the various tournaments the player has participated in.
         *
         */
        highlanderTournaments: Array<HighlanderTournament>;
        /**
         * Contains details about the next 4 matches the player's team is schedule to participate in.
         *
         */
        scheduleItems: Array<MatchScheduleItem>;
        teams: Array<HighlanderTeam>;
        /**
         * The stats displayed here are for the player during the tournament specified in the url
         *
         */
        playerStatsSummaries?: [
            {
                playerId: string;
                kdaRatio: number;
                kdaRatioRank: number;
                csPerTenMinutes: number;
                csPerTenMinutesRank: number;
                killParticipation: number;
                killParticipationRank: number;
                mostplayedchampions: Array<{
                    championId: number;
                    wins: number;
                    losses: number;
                    total: number;
                    kdaRatio: number;
                }>;
            }
        ];
        /**
         * Displays stats from the recently played matches in that particular tournaments.
         * The array starts with the most recently played match.
         *
         */
        playerStatsHistories?: Array<{
            id: string;
            playerId: string;
            championId: number;
            /**
             * Unix timestamp in milliseconds of when the match started.
             */
            timestamp: bigint;
            assists: number;
            deaths: number;
            kills: number;
            csPerTenMinutes: number;
            kdaRatio: number;
            killParticipation: number;
            win: true | false;
            /**
             * The match ID
             */
            match: string;
            /**
             * The team ID the player playes for.
             */
            team: number;
            /**
             * The opponent's team ID.
             */
            opponent: number;
            /**
             * The game ID
             */
            game: string;
        }>;
    };
};

export type PlayersResponse = PlayersResponses[keyof PlayersResponses];
