// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { getCompletedEvents, getDetails, getEventDetails, getGames, getLeagues, getLive, getSchedule, getStandings, getTeams, getTournamentsForLeague, getWindow, highlanderTournaments, leagues, navItems, type Options, players, scheduleItems, teams, videos } from '../sdk.gen';
import type { GetCompletedEventsData, GetCompletedEventsResponse, GetDetailsData, GetDetailsResponse, GetEventDetailsData, GetEventDetailsResponse, GetGamesData, GetGamesResponse, GetLeaguesData, GetLeaguesResponse, GetLiveData, GetLiveResponse, GetScheduleData, GetScheduleResponse, GetStandingsData, GetStandingsResponse, GetTeamsData, GetTeamsResponse, GetTournamentsForLeagueData, GetTournamentsForLeagueResponse, GetWindowData, GetWindowResponse, HighlanderTournamentsData, HighlanderTournamentsError, HighlanderTournamentsResponse, LeaguesData, LeaguesError, LeaguesResponse, NavItemsData, NavItemsResponse, PlayersData, PlayersResponse, ScheduleItemsData, ScheduleItemsResponse, TeamsData, TeamsResponse, VideosData, VideosResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getLeaguesQueryKey = (options: Options<GetLeaguesData>) => createQueryKey('getLeagues', options);

export const getLeaguesOptions = (options: Options<GetLeaguesData>) => queryOptions<GetLeaguesResponse, DefaultError, GetLeaguesResponse, ReturnType<typeof getLeaguesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getLeagues({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getLeaguesQueryKey(options)
});

export const getScheduleQueryKey = (options: Options<GetScheduleData>) => createQueryKey('getSchedule', options);

export const getScheduleOptions = (options: Options<GetScheduleData>) => queryOptions<GetScheduleResponse, DefaultError, GetScheduleResponse, ReturnType<typeof getScheduleQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getSchedule({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getScheduleQueryKey(options)
});

export const getLiveQueryKey = (options: Options<GetLiveData>) => createQueryKey('getLive', options);

export const getLiveOptions = (options: Options<GetLiveData>) => queryOptions<GetLiveResponse, DefaultError, GetLiveResponse, ReturnType<typeof getLiveQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getLive({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getLiveQueryKey(options)
});

export const getTournamentsForLeagueQueryKey = (options: Options<GetTournamentsForLeagueData>) => createQueryKey('getTournamentsForLeague', options);

export const getTournamentsForLeagueOptions = (options: Options<GetTournamentsForLeagueData>) => queryOptions<GetTournamentsForLeagueResponse, DefaultError, GetTournamentsForLeagueResponse, ReturnType<typeof getTournamentsForLeagueQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getTournamentsForLeague({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getTournamentsForLeagueQueryKey(options)
});

export const getStandingsQueryKey = (options: Options<GetStandingsData>) => createQueryKey('getStandings', options);

export const getStandingsOptions = (options: Options<GetStandingsData>) => queryOptions<GetStandingsResponse, DefaultError, GetStandingsResponse, ReturnType<typeof getStandingsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getStandings({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getStandingsQueryKey(options)
});

export const getCompletedEventsQueryKey = (options: Options<GetCompletedEventsData>) => createQueryKey('getCompletedEvents', options);

export const getCompletedEventsOptions = (options: Options<GetCompletedEventsData>) => queryOptions<GetCompletedEventsResponse, DefaultError, GetCompletedEventsResponse, ReturnType<typeof getCompletedEventsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCompletedEvents({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCompletedEventsQueryKey(options)
});

export const getEventDetailsQueryKey = (options: Options<GetEventDetailsData>) => createQueryKey('getEventDetails', options);

export const getEventDetailsOptions = (options: Options<GetEventDetailsData>) => queryOptions<GetEventDetailsResponse, DefaultError, GetEventDetailsResponse, ReturnType<typeof getEventDetailsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getEventDetails({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getEventDetailsQueryKey(options)
});

export const getTeamsQueryKey = (options: Options<GetTeamsData>) => createQueryKey('getTeams', options);

export const getTeamsOptions = (options: Options<GetTeamsData>) => queryOptions<GetTeamsResponse, DefaultError, GetTeamsResponse, ReturnType<typeof getTeamsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getTeams({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getTeamsQueryKey(options)
});

export const getGamesQueryKey = (options: Options<GetGamesData>) => createQueryKey('getGames', options);

export const getGamesOptions = (options: Options<GetGamesData>) => queryOptions<GetGamesResponse, DefaultError, GetGamesResponse, ReturnType<typeof getGamesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getGames({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getGamesQueryKey(options)
});

export const getWindowQueryKey = (options: Options<GetWindowData>) => createQueryKey('getWindow', options);

export const getWindowOptions = (options: Options<GetWindowData>) => queryOptions<GetWindowResponse, DefaultError, GetWindowResponse, ReturnType<typeof getWindowQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getWindow({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getWindowQueryKey(options)
});

export const getDetailsQueryKey = (options: Options<GetDetailsData>) => createQueryKey('getDetails', options);

export const getDetailsOptions = (options: Options<GetDetailsData>) => queryOptions<GetDetailsResponse, DefaultError, GetDetailsResponse, ReturnType<typeof getDetailsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getDetails({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getDetailsQueryKey(options)
});

export const navItemsQueryKey = (options?: Options<NavItemsData>) => createQueryKey('navItems', options);

export const navItemsOptions = (options?: Options<NavItemsData>) => queryOptions<NavItemsResponse, DefaultError, NavItemsResponse, ReturnType<typeof navItemsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await navItems({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: navItemsQueryKey(options)
});

export const videosQueryKey = (options?: Options<VideosData>) => createQueryKey('videos', options);

/**
 * This endpoint returns details about esports vods on YouTube.
 *
 * The data returned by this endpoint is fairly large (more than 5MB) since
 * it includes vods from 2015 up to (at the time of writing this) June 2019
 * and it will continue growing.
 *
 * Do consider this when dealing with clients (like mobile phones) where
 * bandwidth and memory may be scarce.
 *
 * It is highly advised that you cache the data from this endpoint.
 *
 */
export const videosOptions = (options?: Options<VideosData>) => queryOptions<VideosResponse, DefaultError, VideosResponse, ReturnType<typeof videosQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await videos({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: videosQueryKey(options)
});

export const highlanderTournamentsQueryKey = (options: Options<HighlanderTournamentsData>) => createQueryKey('highlanderTournaments', options);

/**
 * If a league does not have highlanderTournament objects, the API will return 404
 *
 */
export const highlanderTournamentsOptions = (options: Options<HighlanderTournamentsData>) => queryOptions<HighlanderTournamentsResponse, HighlanderTournamentsError, HighlanderTournamentsResponse, ReturnType<typeof highlanderTournamentsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await highlanderTournaments({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: highlanderTournamentsQueryKey(options)
});

export const leaguesQueryKey = (options: Options<LeaguesData>) => createQueryKey('leagues', options);

export const leaguesOptions = (options: Options<LeaguesData>) => queryOptions<LeaguesResponse, LeaguesError, LeaguesResponse, ReturnType<typeof leaguesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await leagues({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: leaguesQueryKey(options)
});

export const scheduleItemsQueryKey = (options: Options<ScheduleItemsData>) => createQueryKey('scheduleItems', options);

export const scheduleItemsOptions = (options: Options<ScheduleItemsData>) => queryOptions<ScheduleItemsResponse, DefaultError, ScheduleItemsResponse, ReturnType<typeof scheduleItemsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await scheduleItems({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: scheduleItemsQueryKey(options)
});

export const teamsQueryKey = (options: Options<TeamsData>) => createQueryKey('teams', options);

/**
 * If the `teamStatsSummaries`, `teamRosterStats` and `teamStatsHistories` keys are not present,
 * then the team did not take part in that particular tournament.
 *
 */
export const teamsOptions = (options: Options<TeamsData>) => queryOptions<TeamsResponse, DefaultError, TeamsResponse, ReturnType<typeof teamsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await teams({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: teamsQueryKey(options)
});

export const playersQueryKey = (options: Options<PlayersData>) => createQueryKey('players', options);

/**
 * If the `playerStatsSummaries` and `playerStatsHistories` keys are not present,
 * then the player did not take part in that particular tournament.
 *
 */
export const playersOptions = (options: Options<PlayersData>) => queryOptions<PlayersResponse, DefaultError, PlayersResponse, ReturnType<typeof playersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await players({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: playersQueryKey(options)
});
